"use client";
import Link from "next/link";
import React, { useReducer, useState } from "react";
import { builderReducer, initialBuilderState, PROOF_TIERS } from "./builder-state";

export default function BuilderPage(){
  const[state,dispatch]=useReducer(builderReducer,initialBuilderState);
  const[openChapters,setOpenChapters]=useState<ReadonlySet<number>>(()=>new Set([initialBuilderState.chapters[1]!.id]));
  const stepCount=state.chapters.reduce((total,chapter)=>total+chapter.steps.length,0);
  function setChapterOpen(chapterId:number,open:boolean){setOpenChapters((current)=>{if(current.has(chapterId)===open)return current;const next=new Set(current);if(open)next.add(chapterId);else next.delete(chapterId);return next;});}
  return <main className="onboarding"><header className="onboarding-header"><Link href="/generate" className="button button-ghost" aria-label="Close manual builder">× Build it yourself</Link><span className="pill" style={{justifySelf:"center"}}>Local-only draft</span><Link href="/path" className="button button-primary desktop-continuation">View example path</Link></header><div className="builder">
    <section className="card builder-side stack"><div className="field"><label htmlFor="mission-name">Mission name</label><input id="mission-name" value={state.missionName} onChange={(event)=>dispatch({type:"set-mission",value:event.target.value})}/></div>
      <fieldset style={{border:0,padding:0}}><legend className="field-label">How will you know you’ve made it?</legend><div className="tabs"><button type="button" onClick={()=>dispatch({type:"set-goal-type",value:"OUTCOME"})} className={state.goalType==="OUTCOME"?"active":""} aria-pressed={state.goalType==="OUTCOME"}>A milestone</button><button type="button" onClick={()=>dispatch({type:"set-goal-type",value:"METRIC"})} className={state.goalType==="METRIC"?"active":""} aria-pressed={state.goalType==="METRIC"}>A number</button></div></fieldset>
      {state.goalType==="OUTCOME"?<p className="muted small">Milestone missions track chapters, evidence and your next step. No percentage bar.</p>:<div className="board-grid"><div className="field"><label htmlFor="now">Now</label><input id="now" inputMode="decimal" value={state.metricNow} onChange={(event)=>dispatch({type:"set-metric",field:"metricNow",value:event.target.value})}/></div><div className="field"><label htmlFor="target">Target</label><input id="target" inputMode="decimal" value={state.metricTarget} onChange={(event)=>dispatch({type:"set-metric",field:"metricTarget",value:event.target.value})}/></div></div>}
      <div className="field"><label htmlFor="why">Why this matters to you</label><textarea id="why" rows={3} value={state.why} onChange={(event)=>dispatch({type:"set-why",value:event.target.value})}/></div><p className="preview-note">Edits live only in this browser session and are not saved or carried into the example Path screen. XP remains determined by fixed verification rules.</p><Link href="/path" className="button button-primary mobile-continuation">View example path</Link>
    </section>
    <section className="stack"><div className="row-between"><h1>Chapters</h1><span className="muted">{state.chapters.length} chapters · {stepCount} steps</span></div><div className="chapter-list">{state.chapters.map((chapter,index)=><details className="card chapter-card" open={openChapters.has(chapter.id)} onToggle={(event)=>setChapterOpen(chapter.id,event.currentTarget.open)} key={chapter.id}><summary>{index+1}. {chapter.title||"Untitled chapter"}</summary><div className="stack" style={{marginTop:"1rem"}}><div className="field"><label htmlFor={`chapter-${chapter.id}`}>Chapter name</label><input id={`chapter-${chapter.id}`} value={chapter.title} onChange={(event)=>dispatch({type:"set-chapter",chapterId:chapter.id,field:"title",value:event.target.value})}/></div><div className="field"><label htmlFor={`goal-${chapter.id}`}>Mini-goal</label><input id={`goal-${chapter.id}`} value={chapter.goal} onChange={(event)=>dispatch({type:"set-chapter",chapterId:chapter.id,field:"goal",value:event.target.value})}/></div>
        {chapter.steps.map((step,stepIndex)=><div className="card compact-card stack" key={step.id}><div className="row-between"><b>Step {stepIndex+1}</b><button type="button" className="button button-ghost" aria-label={`Remove step ${stepIndex+1} from chapter ${index+1}`} onClick={()=>dispatch({type:"remove-step",chapterId:chapter.id,stepId:step.id})}>Remove</button></div><div className="field"><label htmlFor={`step-${step.id}`}>What will you do?</label><input id={`step-${step.id}`} value={step.title} onChange={(event)=>dispatch({type:"set-step",chapterId:chapter.id,stepId:step.id,field:"title",value:event.target.value})}/></div><div className="field"><label htmlFor={`when-${step.id}`}>When</label><input id={`when-${step.id}`} value={step.when} onChange={(event)=>dispatch({type:"set-step",chapterId:chapter.id,stepId:step.id,field:"when",value:event.target.value})}/></div><button type="button" className="chip" aria-label={`Proof: ${step.proof}. Activate to change`} onClick={()=>dispatch({type:"cycle-proof",chapterId:chapter.id,stepId:step.id})}>{step.proof} · {PROOF_TIERS.indexOf(step.proof)+1} of {PROOF_TIERS.length}</button></div>)}
        <button className="button button-secondary" type="button" onClick={()=>dispatch({type:"add-step",chapterId:chapter.id})}>+ Add step</button></div></details>)}</div><button className="button button-secondary" type="button" onClick={()=>dispatch({type:"add-chapter"})}>+ Add chapter</button>
    </section>
  </div></main>;
}
