import { db } from "@/lib/db";
import { addWeeks } from "date-fns";
import { projectPace, type PaceProjection } from "./pace";

export { projectPace };
export type { PaceInput, PaceProjection } from "./pace";

/**
 * Adaptive planning. Recomputes milestone ETAs and goal progress from the
 * user's *actual* throughput, then emits AiRecommendation rows when the plan
 * and reality have diverged (ahead of schedule, behind, stalled, deadline risk).
 *
 * Pure projection maths lives in ./pace.ts and is unit tested.
 */

/** Recompute one goal's milestone ETAs + progress, and refresh recommendations. */
export async function recomputeGoalPlan(goalId: string) {
  const goal = await db.goal.findUnique({
    where: { id: goalId },
    include: { milestones: { orderBy: { orderIndex: "asc" } }, skills: true },
  });
  if (!goal) return;

  const activeDaysLast14 = await db.taskCompletion
    .findMany({
      where: { task: { goalId }, completedAt: { gte: new Date(Date.now() - 14 * 864e5) } },
      select: { completedAt: true },
    })
    .then((rows) => new Set(rows.map((r) => r.completedAt.toISOString().slice(0, 10))).size);

  const profile = await db.profile.findUnique({ where: { userId: goal.userId } });

  const pace = projectPace({
    progressPct: goal.progressPct,
    startedAt: goal.startedAt,
    timelineWeeks: goal.timelineWeeks,
    targetDate: goal.targetDate,
    activeDaysLast14,
    plannedDaysPerWeek: profile?.weeklyDays ?? 5,
  });

  // Re-space unfinished milestone due dates across the remaining schedule.
  const openMs = goal.milestones.filter((m) => m.status !== "done");
  if (openMs.length && (goal.timelineWeeks || goal.targetDate)) {
    const endDate = goal.targetDate ?? addWeeks(goal.startedAt, goal.timelineWeeks ?? 12);
    const now = new Date();
    const spanMs = Math.max(1, endDate.getTime() - now.getTime());
    for (let i = 0; i < openMs.length; i++) {
      const due = new Date(now.getTime() + (spanMs * (i + 1)) / openMs.length);
      await db.milestone.update({ where: { id: openMs[i]!.id }, data: { dueDate: due } });
    }
  }

  await refreshRecommendations(goal.id, goal.userId, pace);
  return pace;
}

async function refreshRecommendations(
  goalId: string,
  userId: string,
  pace: PaceProjection,
) {
  // clear stale auto recommendations of the pace/plan kind for this goal
  await db.aiRecommendation.deleteMany({
    where: { goalId, kind: { in: ["pace", "plan_change"] }, status: { in: ["new", "seen"] }, rationale: { startsWith: "[auto]" } },
  });

  const mk = (kind: string, title: string, body: string, priority: number) =>
    db.aiRecommendation.create({
      data: { userId, goalId, kind, title, body, rationale: "[auto] generated by adaptive planner", priority },
    });

  if (pace.status === "stalled") {
    await mk("pace", "This goal has stalled", "No measurable progress in over a week. Do one small task today to restart momentum — pick the easiest open task.", 1);
  } else if (pace.status === "behind") {
    await mk(
      "pace",
      "Behind schedule",
      `You're about ${Math.abs(Math.round(pace.deltaPct))}% behind where the plan expects you to be${
        pace.projectedDoneDate ? `. At the current rate you'd finish around ${pace.projectedDoneDate.toISOString().slice(0, 10)}` : ""
      }. Add one extra session per week, or push the target date.`,
      2,
    );
  } else if (pace.status === "ahead") {
    await mk("pace", "Ahead of schedule", `You're ~${Math.round(pace.deltaPct)}% ahead of plan. Consider raising the target level or pulling the deadline forward.`, 3);
  }

  if (pace.adherence < 0.5 && pace.status !== "stalled") {
    await mk("pace", "Consistency slipping", `You've hit roughly ${Math.round(pace.adherence * 100)}% of your planned sessions lately. Shrink tasks or lower your daily-minutes target so the habit sticks.`, 2);
  }
}

/** Nightly-ish job: refresh every active goal for a user. Call after login too. */
export async function recomputeAllGoals(userId: string) {
  const goals = await db.goal.findMany({ where: { userId, status: "active" }, select: { id: true } });
  for (const g of goals) await recomputeGoalPlan(g.id).catch(() => {});
}
