import { renderToStaticMarkup } from "react-dom/server";
import React from "react";
import { describe,expect,it } from "vitest";
import type { PipelineResult } from "@zandegi/ai";
import { MissionReview } from "./mission-review";

function result(goalType:"OUTCOME"|"METRIC",professionalFrameApplied=false):PipelineResult{return {event:{type:"MissionGenerated",occurredAt:"2026-01-01T00:00:00Z",payload:{goalText:"Become a doctor",pursuitSlug:"medicine",mission:{title:"Become a doctor",goalType,primaryDomain:"Mind",completionXp:400,chapters:[{index:0,title:"Know the pathway",exitCondition:"Gather entry evidence",completionXp:100,steps:[{index:0,title:"Read entry requirements",estimatedMinutes:30,verification:"ARTIFACT",guide:{approach:"Capture the official requirements.",materials:[],commonMistakes:[],whatGoodLooksLike:"A dated note."},toolKinds:[],sources:[],baseXp:30}]}]},grounding:{claimsChecked:0,ungroundedClaims:[],rewritten:0,dropped:0},safety:{safetyClass:professionalFrameApplied?"CLINICAL":"NORMAL",blocked:false,professionalFrameApplied,redactions:[]},generationMeta:{modelsUsed:{},totalMs:1}}},refusal:undefined}}

describe("mission review",()=>{it("uses qualitative progress for outcome goals and semantic disclosure controls",()=>{const html=renderToStaticMarkup(<MissionReview result={result("OUTCOME")}/>);expect(html).toContain("Honest progress");expect(html).not.toContain("Measurable progress");expect(html).toContain("<details");expect(html).toContain("View example path");expect(html).toContain("will not carry over")});it("allows measurable progress framing for metric goals",()=>{expect(renderToStaticMarkup(<MissionReview result={result("METRIC")}/>)).toContain("Measurable progress")});it("renders professional-guidance safety context when applied",()=>{const html=renderToStaticMarkup(<MissionReview result={result("OUTCOME",true)}/>);expect(html).toContain("Professional guidance applies");expect(html).toContain("qualified professional")})});
