import type { TemplateDomain, TemplateSpec } from "../types";

interface Subject {
  slug: string;
  name: string;
  /** The thing that actually makes this subject hard. */
  crux: string;
  /** What mastery looks like in practice. */
  application: string;
}

const SUBJECTS: Subject[] = [
  { slug: "algebra", name: "algebra", crux: "Manipulating expressions fluently", application: "Solve unfamiliar problems unaided" },
  { slug: "calculus", name: "calculus", crux: "Limits, derivatives and integrals", application: "Solve applied optimisation problems" },
  { slug: "linear-algebra", name: "linear algebra", crux: "Vector spaces and transformations", application: "Apply it to real data or graphics problems" },
  { slug: "statistics", name: "statistics", crux: "Inference and uncertainty", application: "Analyse a real dataset correctly" },
  { slug: "probability", name: "probability", crux: "Distributions and conditional reasoning", application: "Model a real random process" },
  { slug: "discrete-maths", name: "discrete mathematics", crux: "Proof and combinatorial reasoning", application: "Write rigorous proofs" },
  { slug: "geometry", name: "geometry", crux: "Spatial reasoning and proof", application: "Prove non-obvious results" },
  { slug: "trigonometry", name: "trigonometry", crux: "Identities and the unit circle", application: "Solve applied triangle and wave problems" },
  { slug: "physics-mechanics", name: "mechanics", crux: "Forces and motion modelling", application: "Solve multi-step dynamics problems" },
  { slug: "physics-electricity", name: "electricity and magnetism", crux: "Fields and circuits", application: "Analyse real circuits and fields" },
  { slug: "physics-quantum", name: "quantum mechanics", crux: "Wavefunctions and operators", application: "Solve standard quantum systems" },
  { slug: "physics-thermo", name: "thermodynamics", crux: "Entropy and state functions", application: "Analyse real thermal systems" },
  { slug: "chemistry-organic", name: "organic chemistry", crux: "Reaction mechanisms", application: "Predict and design syntheses" },
  { slug: "chemistry-inorganic", name: "inorganic chemistry", crux: "Periodic trends and bonding", application: "Predict structure and reactivity" },
  { slug: "chemistry-physical", name: "physical chemistry", crux: "Kinetics and equilibria", application: "Solve quantitative problems" },
  { slug: "biology-cell", name: "cell biology", crux: "Processes and their regulation", application: "Explain mechanisms from first principles" },
  { slug: "biology-genetics", name: "genetics", crux: "Inheritance and molecular mechanisms", application: "Solve genetics problems and read papers" },
  { slug: "biology-ecology", name: "ecology", crux: "Systems and population dynamics", application: "Interpret ecological data" },
  { slug: "anatomy", name: "human anatomy", crux: "Structure, relationships and volume of detail", application: "Identify structures and explain function" },
  { slug: "physiology", name: "physiology", crux: "Integrated system regulation", application: "Reason through clinical scenarios" },
  { slug: "neuroscience", name: "neuroscience", crux: "Linking cells to behaviour", application: "Read and critique primary literature" },
  { slug: "pharmacology", name: "pharmacology", crux: "Drug mechanisms and kinetics", application: "Reason about drug choice and interactions" },
  { slug: "economics-micro", name: "microeconomics", crux: "Modelling incentives and markets", application: "Analyse real market behaviour" },
  { slug: "economics-macro", name: "macroeconomics", crux: "Aggregate models and policy", application: "Interpret real economic data" },
  { slug: "econometrics", name: "econometrics", crux: "Identification and inference", application: "Run and defend a regression analysis" },
  { slug: "accounting", name: "accounting", crux: "Double entry and the statements", application: "Prepare and read full financial statements" },
  { slug: "history", name: "history", crux: "Argument from evidence", application: "Write a well-sourced historical argument" },
  { slug: "philosophy", name: "philosophy", crux: "Rigorous argument analysis", application: "Construct and defend an argument" },
  { slug: "psychology", name: "psychology", crux: "Method and evidence quality", application: "Critique a study properly" },
  { slug: "sociology", name: "sociology", crux: "Theory applied to evidence", application: "Analyse a social phenomenon" },
  { slug: "politics", name: "political science", crux: "Institutions and comparative analysis", application: "Analyse a political system" },
  { slug: "law-contract", name: "contract law", crux: "Applying rules to messy facts", application: "Answer a problem question well" },
  { slug: "literature", name: "literature", crux: "Close reading and interpretation", application: "Write a persuasive critical essay" },
  { slug: "linguistics", name: "linguistics", crux: "Formal analysis of language", application: "Analyse unfamiliar language data" },
  { slug: "geography", name: "geography", crux: "Linking physical and human systems", application: "Interpret and explain spatial patterns" },
  { slug: "geology", name: "geology", crux: "Reading time from rock", application: "Interpret a geological map" },
  { slug: "astronomy", name: "astronomy", crux: "Scale and observational reasoning", application: "Interpret real astronomical data" },
  { slug: "computer-science", name: "computer science theory", crux: "Abstraction and complexity", application: "Analyse algorithms rigorously" },
  { slug: "art-history", name: "art history", crux: "Visual analysis in context", application: "Analyse an unfamiliar work convincingly" },
  { slug: "music-history", name: "music history", crux: "Style and context", application: "Place and analyse an unfamiliar work" },
];

function masterSubject(s: Subject): TemplateSpec {
  return {
    key: `academic-master-${s.slug}`,
    title: `Master ${s.name}`,
    summary: `Build real understanding of ${s.name} — not just passing familiarity. ${s.crux} is the part that decides whether it clicks.`,
    category: "education",
    difficulty: 4,
    weeks: 32,
    tags: [s.slug.replace(/-/g, " "), s.name, "study", "academic", "learning"],
    skills: ["Foundational concepts", s.crux, "Problem solving", "Spaced review", "Application and transfer"],
    milestones: [
      "Foundations solid and gaps identified",
      "Core material covered once",
      "Solving standard problems reliably",
      s.application,
    ],
  };
}

const generated = SUBJECTS.map(masterSubject);

const extras: TemplateSpec[] = [
  {
    key: "academic-graduate-honours",
    title: "Graduate with honours",
    summary: "Lift your grade average enough to finish your degree with honours, working back from what each unit needs.",
    category: "education",
    difficulty: 4,
    weeks: 52,
    tags: ["honours", "degree", "university", "grades", "gpa"],
    skills: ["Grade-target planning", "Deep study technique", "Assessment strategy", "Time and workload management", "Feedback loops with staff"],
    milestones: ["Required marks per unit calculated", "Study system running weekly", "First semester on target", "Honours average achieved"],
  },
  {
    key: "academic-first-class-degree",
    title: "Finish your degree with top marks",
    summary: "A sustained plan to reach the highest classification your institution awards.",
    category: "education",
    difficulty: 5,
    weeks: 80,
    tags: ["first class", "gpa", "distinction", "university", "degree"],
    skills: ["Assessment strategy", "Deep study technique", "Exam performance", "Research and writing quality", "Sustainable workload"],
    milestones: ["Baseline average known", "Study system proven over a semester", "Consistent top marks", "Degree completed at target classification"],
  },
  {
    key: "academic-get-into-university",
    title: "Get into your first-choice university",
    summary: "Work backwards from the entry requirements and build an application that clears them.",
    category: "education",
    difficulty: 4,
    weeks: 52,
    tags: ["university", "admissions", "application", "entry"],
    skills: ["Entry requirement mapping", "Academic performance", "Admissions test preparation", "Personal statement", "Interview preparation"],
    milestones: ["Requirements and deadlines mapped", "Grades on track", "Application submitted", "Offer received"],
  },
  {
    key: "academic-standardised-test",
    title: "Score highly on a university admissions test",
    summary: "Structured preparation for a timed admissions test, whichever one your country uses.",
    category: "exam",
    difficulty: 4,
    weeks: 30,
    tags: ["admissions test", "entrance exam", "aptitude", "timed"],
    skills: ["Content mastery", "Timing and exam technique", "Practice-test analysis", "Weak-area remediation", "Test-day readiness"],
    milestones: ["Diagnostic sat, baseline set", "All content covered once", "Consistent timing under pressure", "Target score on full mocks", "Sit the real test"],
  },
  {
    key: "academic-final-exams",
    title: "Prepare properly for final exams",
    summary: "Replace last-minute cramming with a spaced, tested schedule that actually holds.",
    category: "exam",
    difficulty: 3,
    weeks: 14,
    tags: ["exams", "revision", "study", "finals"],
    skills: ["Syllabus mapping", "Active recall", "Spaced repetition", "Past-paper practice", "Exam technique"],
    milestones: ["Syllabus mapped and scheduled", "First pass through all content", "Past papers under timed conditions", "Exams sat"],
  },
  {
    key: "academic-dissertation",
    title: "Write your dissertation or thesis",
    summary: "Break a large piece of independent research into a schedule you can actually keep.",
    category: "research",
    difficulty: 4,
    weeks: 40,
    tags: ["dissertation", "thesis", "research", "writing"],
    skills: ["Research question framing", "Literature review", "Methodology", "Data analysis", "Academic writing", "Supervisor relationship"],
    milestones: ["Question and scope agreed", "Literature review drafted", "Data collected", "Full draft submitted to supervisor", "Final version submitted"],
  },
  {
    key: "academic-study-technique",
    title: "Learn how to actually study",
    summary: "Replace re-reading and highlighting with techniques that are known to work.",
    category: "education",
    difficulty: 2,
    weeks: 10,
    tags: ["study skills", "active recall", "spaced repetition", "learning"],
    skills: ["Active recall", "Spaced repetition", "Interleaving", "Self-testing", "Session planning"],
    milestones: ["Current habits audited", "Recall and spacing in daily use", "System survives a busy week", "Measurable improvement in retention"],
  },
  {
    key: "academic-speed-reading",
    title: "Read academic material faster and retain it",
    summary: "Get through dense reading efficiently without losing comprehension.",
    category: "education",
    difficulty: 2,
    weeks: 8,
    tags: ["reading", "comprehension", "academic", "speed"],
    skills: ["Previewing and structure", "Selective depth", "Note-taking while reading", "Retention checks"],
    milestones: ["Baseline speed and recall measured", "Structured previewing habitual", "Notes genuinely useful later", "Faster with equal comprehension"],
  },
  {
    key: "academic-scholarship",
    title: "Win a scholarship",
    summary: "Find the ones you are genuinely competitive for and build an application that stands out.",
    category: "education",
    difficulty: 3,
    weeks: 24,
    tags: ["scholarship", "funding", "application", "bursary"],
    skills: ["Opportunity research", "Eligibility matching", "Written application", "References", "Interview preparation"],
    milestones: ["Shortlist of ten built", "First application submitted", "Five applications submitted", "Scholarship awarded"],
  },
  {
    key: "academic-learn-to-write",
    title: "Write better academic essays",
    summary: "Argument structure, evidence and clarity — the parts that actually move marks.",
    category: "education",
    difficulty: 3,
    weeks: 16,
    tags: ["essay", "writing", "argument", "academic"],
    skills: ["Argument structure", "Evidence and citation", "Clarity and editing", "Responding to feedback"],
    milestones: ["Structure template working", "Essay written with clear thesis", "Feedback incorporated", "Consistent grade improvement"],
  },
  {
    key: "academic-online-course",
    title: "Actually finish an online course",
    summary: "Beat the 90% dropout rate with scheduling, accountability and applied projects.",
    category: "education",
    difficulty: 2,
    weeks: 12,
    tags: ["online course", "mooc", "self-study", "completion"],
    skills: ["Realistic scheduling", "Active note-taking", "Applied practice", "Accountability"],
    milestones: ["Schedule set and protected", "25% complete", "75% complete", "Course finished with a project"],
  },
  {
    key: "academic-teach-yourself",
    title: "Teach yourself a subject with no course",
    summary: "Build your own curriculum, sequence and assessment when nobody hands you one.",
    category: "education",
    difficulty: 4,
    weeks: 36,
    tags: ["self-directed", "autodidact", "curriculum", "learning"],
    skills: ["Curriculum design", "Source selection", "Progressive problem sets", "Self-assessment", "Knowledge gaps hunting"],
    milestones: ["Syllabus written", "Foundations covered", "Midpoint self-assessment passed", "Capstone project completed"],
  },
];

export const academic: TemplateDomain = {
  key: "academic",
  label: "Study & academia",
  blurb: "Subjects, exams, degrees, research and learning how to learn.",
  templates: [...generated, ...extras],
};
