import type { TemplateDomain, TemplateSpec } from "../types";

interface Profession {
  slug: string;
  name: string;
  /** Core competence that defines the job. */
  craft: string;
  /** Evidence that gets you hired in this field. */
  evidence: string;
  /** Roughly how long a career transition takes, in weeks. */
  weeks: number;
  difficulty: number;
}

const PROFESSIONS: Profession[] = [
  { slug: "software-engineer", name: "a software engineer", craft: "Programming and system design", evidence: "Portfolio of shipped projects", weeks: 60, difficulty: 4 },
  { slug: "data-scientist", name: "a data scientist", craft: "Statistics and modelling", evidence: "Portfolio of analyses", weeks: 60, difficulty: 4 },
  { slug: "ux-designer", name: "a UX designer", craft: "Research and interaction design", evidence: "Case-study portfolio", weeks: 48, difficulty: 3 },
  { slug: "graphic-designer", name: "a graphic designer", craft: "Visual design and typography", evidence: "Design portfolio", weeks: 44, difficulty: 3 },
  { slug: "product-manager", name: "a product manager", craft: "Discovery and prioritisation", evidence: "Shipped product outcomes", weeks: 52, difficulty: 4 },
  { slug: "project-manager", name: "a project manager", craft: "Planning and stakeholder management", evidence: "Delivered projects and certification", weeks: 40, difficulty: 3 },
  { slug: "accountant", name: "an accountant", craft: "Financial reporting and compliance", evidence: "Professional qualification", weeks: 96, difficulty: 4 },
  { slug: "lawyer", name: "a lawyer", craft: "Legal reasoning and drafting", evidence: "Qualification and practical training", weeks: 200, difficulty: 5 },
  { slug: "doctor", name: "a doctor", craft: "Clinical reasoning and patient care", evidence: "Medical degree and placements", weeks: 300, difficulty: 5 },
  { slug: "nurse", name: "a nurse", craft: "Clinical care and assessment", evidence: "Nursing registration", weeks: 150, difficulty: 5 },
  { slug: "paramedic", name: "a paramedic", craft: "Emergency assessment and care", evidence: "Paramedic registration", weeks: 150, difficulty: 5 },
  { slug: "physiotherapist", name: "a physiotherapist", craft: "Assessment and rehabilitation", evidence: "Professional registration", weeks: 150, difficulty: 5 },
  { slug: "psychologist", name: "a psychologist", craft: "Assessment and therapeutic practice", evidence: "Registration and supervised hours", weeks: 250, difficulty: 5 },
  { slug: "teacher", name: "a teacher", craft: "Pedagogy and classroom practice", evidence: "Teaching qualification", weeks: 100, difficulty: 4 },
  { slug: "architect", name: "an architect", craft: "Design and technical documentation", evidence: "Registration and portfolio", weeks: 250, difficulty: 5 },
  { slug: "civil-engineer", name: "a civil engineer", craft: "Structural and site engineering", evidence: "Degree and chartership", weeks: 200, difficulty: 5 },
  { slug: "electrician", name: "an electrician", craft: "Electrical installation and safety", evidence: "Trade licence", weeks: 150, difficulty: 4 },
  { slug: "plumber", name: "a plumber", craft: "Plumbing installation and repair", evidence: "Trade licence", weeks: 150, difficulty: 4 },
  { slug: "carpenter", name: "a carpenter", craft: "Joinery and construction", evidence: "Trade qualification and portfolio", weeks: 150, difficulty: 4 },
  { slug: "chef", name: "a chef", craft: "Cooking technique and kitchen speed", evidence: "Kitchen experience and references", weeks: 100, difficulty: 4 },
  { slug: "pilot", name: "a pilot", craft: "Flying and airmanship", evidence: "Commercial licence and hours", weeks: 150, difficulty: 5 },
  { slug: "journalist", name: "a journalist", craft: "Reporting and writing", evidence: "Published clippings", weeks: 52, difficulty: 4 },
  { slug: "copywriter", name: "a copywriter", craft: "Persuasive writing", evidence: "Portfolio and client work", weeks: 36, difficulty: 3 },
  { slug: "marketer", name: "a marketer", craft: "Audience, channels and measurement", evidence: "Campaign results", weeks: 40, difficulty: 3 },
  { slug: "salesperson", name: "a salesperson", craft: "Discovery and closing", evidence: "Quota performance", weeks: 36, difficulty: 3 },
  { slug: "recruiter", name: "a recruiter", craft: "Sourcing and candidate assessment", evidence: "Placement record", weeks: 32, difficulty: 3 },
  { slug: "hr-professional", name: "an HR professional", craft: "People operations and employment practice", evidence: "Qualification and experience", weeks: 44, difficulty: 3 },
  { slug: "financial-analyst", name: "a financial analyst", craft: "Valuation and financial modelling", evidence: "Modelling portfolio and certification", weeks: 60, difficulty: 4 },
  { slug: "consultant", name: "a management consultant", craft: "Structured problem solving", evidence: "Case interview performance", weeks: 44, difficulty: 4 },
  { slug: "entrepreneur", name: "a founder", craft: "Customer discovery and execution", evidence: "A business with real revenue", weeks: 80, difficulty: 5 },
  { slug: "photographer", name: "a professional photographer", craft: "Composition and lighting", evidence: "Portfolio and paying clients", weeks: 52, difficulty: 3 },
  { slug: "videographer", name: "a videographer", craft: "Shooting and editing", evidence: "Showreel and client work", weeks: 48, difficulty: 3 },
  { slug: "animator", name: "an animator", craft: "Motion and timing", evidence: "Showreel", weeks: 60, difficulty: 4 },
  { slug: "game-developer", name: "a game developer", craft: "Engine work and gameplay programming", evidence: "Shipped games", weeks: 72, difficulty: 4 },
  { slug: "translator", name: "a translator", craft: "Translation accuracy and register", evidence: "Accreditation and client work", weeks: 60, difficulty: 4 },
  { slug: "social-worker", name: "a social worker", craft: "Casework and advocacy", evidence: "Qualification and placements", weeks: 150, difficulty: 4 },
  { slug: "veterinarian", name: "a vet", craft: "Animal clinical care", evidence: "Veterinary registration", weeks: 250, difficulty: 5 },
  { slug: "dentist", name: "a dentist", craft: "Clinical dentistry", evidence: "Dental registration", weeks: 250, difficulty: 5 },
  { slug: "pharmacist", name: "a pharmacist", craft: "Pharmacology and dispensing", evidence: "Pharmacy registration", weeks: 200, difficulty: 5 },
  { slug: "electrical-engineer", name: "an electrical engineer", craft: "Circuits and systems design", evidence: "Degree and project portfolio", weeks: 200, difficulty: 5 },
  { slug: "mechanical-engineer", name: "a mechanical engineer", craft: "Mechanics and design", evidence: "Degree and project portfolio", weeks: 200, difficulty: 5 },
  { slug: "personal-trainer", name: "a personal trainer", craft: "Programming and coaching", evidence: "Certification and client results", weeks: 28, difficulty: 3 },
  { slug: "therapist", name: "a therapist", craft: "Therapeutic technique", evidence: "Qualification and supervised hours", weeks: 200, difficulty: 5 },
  { slug: "electrician-solar", name: "a solar installer", craft: "PV system installation", evidence: "Accreditation and installs", weeks: 40, difficulty: 3 },
  { slug: "pilot-drone", name: "a commercial drone pilot", craft: "Flight operations and airspace rules", evidence: "Licence and logged hours", weeks: 20, difficulty: 3 },
];

function becomeProfession(p: Profession): TemplateSpec {
  return {
    key: `career-become-${p.slug}`,
    title: `Become ${p.name}`,
    summary: `Map the qualifications, skills and evidence needed, then work through them to get hired as ${p.name}.`,
    category: "career",
    difficulty: p.difficulty,
    weeks: p.weeks,
    tags: [p.slug.replace(/-/g, " "), "career", "profession", "job", "training"],
    skills: [p.craft, "Required qualifications", "Practical experience", "Professional network", "Applications and interviews"],
    milestones: [
      "Entry requirements mapped and route chosen",
      "Core training underway",
      p.evidence,
      "Applying with a competitive profile",
      `Working as ${p.name}`,
    ],
  };
}

const generated = PROFESSIONS.map(becomeProfession);

const extras: TemplateSpec[] = [
  {
    key: "career-get-promoted",
    title: "Get promoted to the next level",
    summary: "Understand what your organisation actually rewards, then build and evidence it deliberately.",
    category: "career",
    difficulty: 3,
    weeks: 40,
    tags: ["promotion", "career", "performance", "progression"],
    skills: ["Expectations mapping", "High-visibility delivery", "Stakeholder relationships", "Evidence and self-advocacy"],
    milestones: ["Criteria understood and agreed", "Owning a high-visibility piece of work", "Evidence documented", "Promotion secured"],
  },
  {
    key: "career-change-industry",
    title: "Change to a completely different industry",
    summary: "Work out what transfers, close the gaps, and reposition yourself credibly.",
    category: "career",
    difficulty: 4,
    weeks: 52,
    tags: ["career change", "pivot", "transition", "industry"],
    skills: ["Transferable skill audit", "Gap closing", "Repositioning your story", "Industry networking", "Targeted applications"],
    milestones: ["Target role and gaps identified", "Key gap closed", "Ten informational conversations", "First interview in the new field", "Offer in the new industry"],
  },
  {
    key: "career-negotiate-salary",
    title: "Negotiate a significant pay rise",
    summary: "Build the case, benchmark properly, and run the conversation without flinching.",
    category: "career",
    difficulty: 2,
    weeks: 12,
    tags: ["salary", "negotiation", "pay rise", "compensation"],
    skills: ["Market benchmarking", "Impact documentation", "Negotiation practice", "Conversation timing"],
    milestones: ["Market rate researched", "Impact case written", "Practised the conversation", "Negotiation held"],
  },
  {
    key: "career-public-speaking",
    title: "Become a confident public speaker",
    summary: "Go from dreading presentations to delivering them well, on purpose.",
    category: "career",
    difficulty: 3,
    weeks: 24,
    tags: ["public speaking", "presenting", "confidence", "communication"],
    skills: ["Structuring a talk", "Delivery and voice", "Managing nerves", "Handling questions", "Repeated exposure"],
    milestones: ["Present to a small friendly group", "Present to your team", "Present to a large internal audience", "Speak at an external event"],
  },
  {
    key: "career-manage-people",
    title: "Become a good first-time manager",
    summary: "The shift from doing the work to being responsible for other people doing it.",
    category: "career",
    difficulty: 4,
    weeks: 40,
    tags: ["management", "leadership", "first-time manager", "people"],
    skills: ["One-to-ones and feedback", "Delegation", "Difficult conversations", "Hiring", "Team performance"],
    milestones: ["Regular one-to-ones running", "Delegated meaningful work", "Handled a difficult conversation well", "Team performing without you in the detail"],
  },
  {
    key: "career-build-network",
    title: "Build a professional network from scratch",
    summary: "Genuine, useful professional relationships rather than collecting connections.",
    category: "career",
    difficulty: 2,
    weeks: 32,
    tags: ["networking", "relationships", "linkedin", "career"],
    skills: ["Outreach that gets replies", "Informational conversations", "Staying in touch", "Being useful to others"],
    milestones: ["First ten conversations", "Regular contact with five people", "Introduced to someone through the network", "Network generating opportunities"],
    metric: { name: "Meaningful conversations", target: 50, unit: "people" },
  },
  {
    key: "career-freelance",
    title: "Go freelance and replace your salary",
    summary: "Build a client base and the business habits to make self-employment stable.",
    category: "business",
    difficulty: 4,
    weeks: 52,
    tags: ["freelance", "self-employed", "clients", "consulting"],
    skills: ["Service definition and pricing", "Client acquisition", "Contracts and invoicing", "Delivery and reputation", "Financial buffer management"],
    milestones: ["Offer and pricing defined", "First paying client", "Three regular clients", "Salary replaced"],
  },
  {
    key: "career-write-cv",
    title: "Rewrite your CV and get interviews",
    summary: "Turn a duties-based CV into an evidence-based one that actually gets callbacks.",
    category: "career",
    difficulty: 1,
    weeks: 6,
    tags: ["cv", "resume", "job search", "applications"],
    skills: ["Impact-led writing", "Tailoring per role", "Formatting and scanning", "Application tracking"],
    milestones: ["Achievements inventoried", "CV rewritten", "Tailored for five roles", "First interview secured"],
  },
  {
    key: "career-portfolio",
    title: "Build a portfolio that gets you hired",
    summary: "Curated, well-presented work that shows how you think, not just what you made.",
    category: "career",
    difficulty: 3,
    weeks: 20,
    tags: ["portfolio", "case study", "creative", "hiring"],
    skills: ["Project selection", "Case-study writing", "Presentation and layout", "Publishing"],
    milestones: ["Best work selected", "First case study written", "Three case studies live", "Portfolio published and shared"],
  },
  {
    key: "career-remote-work",
    title: "Land a fully remote job",
    summary: "Target genuinely remote roles and prove you can work well without supervision.",
    category: "career",
    difficulty: 3,
    weeks: 32,
    tags: ["remote", "work from home", "distributed", "job search"],
    skills: ["Remote-friendly skill set", "Written communication", "Targeted job search", "Remote interview performance"],
    milestones: ["Remote-ready CV and profile", "Written communication samples ready", "First remote interview", "Remote offer accepted"],
  },
  {
    key: "career-phd",
    title: "Complete a PhD",
    summary: "The full arc from proposal to defended thesis, paced so it stays survivable.",
    category: "research",
    difficulty: 5,
    weeks: 200,
    tags: ["phd", "research", "thesis", "academia", "doctorate"],
    skills: ["Literature command", "Research methodology", "Data collection and analysis", "Academic writing", "Supervision relationship", "Conference presenting"],
    milestones: ["Proposal accepted", "Literature review complete", "Data collection finished", "Full draft written", "Thesis defended"],
  },
  {
    key: "career-publish-paper",
    title: "Publish a peer-reviewed paper",
    summary: "Take a piece of research from question to accepted publication.",
    category: "research",
    difficulty: 4,
    weeks: 52,
    tags: ["research", "publication", "peer review", "academia"],
    skills: ["Research question framing", "Methodology", "Academic writing", "Journal selection", "Responding to reviewers"],
    milestones: ["Question and method settled", "Results in hand", "Manuscript submitted", "Revisions accepted", "Published"],
  },
];

export const career: TemplateDomain = {
  key: "career",
  label: "Career & work",
  blurb: "Entering a profession, progressing, changing direction and working for yourself.",
  templates: [...generated, ...extras],
};
