import type { TemplateDomain, TemplateSpec } from "../types";

interface Medium {
  slug: string;
  name: string;
  /** The fundamental that beginners most often skip. */
  fundamental: string;
  /** A finished thing that proves competence. */
  artefact: string;
  hard?: boolean;
}

const MEDIA: Medium[] = [
  { slug: "drawing", name: "drawing", fundamental: "Observation and proportion", artefact: "A finished drawing you are proud of" },
  { slug: "sketching", name: "sketching from life", fundamental: "Fast observation", artefact: "A filled sketchbook" },
  { slug: "portraits", name: "portrait drawing", fundamental: "Facial proportion and structure", artefact: "A recognisable likeness", hard: true },
  { slug: "figure-drawing", name: "figure drawing", fundamental: "Gesture and anatomy", artefact: "A confident figure study", hard: true },
  { slug: "watercolour", name: "watercolour painting", fundamental: "Water control and layering", artefact: "A finished watercolour" },
  { slug: "oil-painting", name: "oil painting", fundamental: "Colour mixing and layering", artefact: "A finished oil painting", hard: true },
  { slug: "acrylic-painting", name: "acrylic painting", fundamental: "Colour mixing and edges", artefact: "A finished acrylic painting" },
  { slug: "gouache", name: "gouache painting", fundamental: "Opaque colour mixing", artefact: "A finished gouache piece" },
  { slug: "digital-painting", name: "digital painting", fundamental: "Values before colour", artefact: "A finished digital illustration" },
  { slug: "illustration", name: "illustration", fundamental: "Composition and storytelling", artefact: "A cohesive set of illustrations" },
  { slug: "comics", name: "making comics", fundamental: "Panel flow and pacing", artefact: "A finished short comic" },
  { slug: "character-design", name: "character design", fundamental: "Silhouette and shape language", artefact: "A full character sheet" },
  { slug: "concept-art", name: "concept art", fundamental: "Design thinking and iteration", artefact: "A portfolio-ready concept piece", hard: true },
  { slug: "animation-2d", name: "2D animation", fundamental: "Timing and spacing", artefact: "A finished short animation", hard: true },
  { slug: "animation-3d", name: "3D animation", fundamental: "Weight and timing", artefact: "A finished animated shot", hard: true },
  { slug: "3d-modelling", name: "3D modelling", fundamental: "Topology and form", artefact: "A finished 3D model", hard: true },
  { slug: "graphic-design", name: "graphic design", fundamental: "Typography and hierarchy", artefact: "A polished design portfolio piece" },
  { slug: "typography", name: "typography", fundamental: "Spacing and type pairing", artefact: "A typographic piece that reads beautifully" },
  { slug: "calligraphy", name: "calligraphy", fundamental: "Consistent stroke control", artefact: "A finished calligraphic piece" },
  { slug: "hand-lettering", name: "hand lettering", fundamental: "Letterform construction", artefact: "A finished lettering piece" },
  { slug: "printmaking", name: "printmaking", fundamental: "Carving and registration", artefact: "An edition of prints" },
  { slug: "photography", name: "photography", fundamental: "Light and composition", artefact: "A cohesive photo series" },
  { slug: "film-photography", name: "film photography", fundamental: "Exposure without a preview", artefact: "A developed roll you are happy with" },
  { slug: "street-photography", name: "street photography", fundamental: "Anticipation and nerve", artefact: "A strong street series" },
  { slug: "portrait-photography", name: "portrait photography", fundamental: "Directing and lighting people", artefact: "A portrait series" },
  { slug: "photo-editing", name: "photo editing", fundamental: "Restraint and consistency", artefact: "A consistently edited portfolio" },
  { slug: "videography", name: "videography", fundamental: "Coverage and continuity", artefact: "A finished short film" },
  { slug: "video-editing", name: "video editing", fundamental: "Pacing and rhythm", artefact: "A polished edited video" },
  { slug: "sculpture", name: "sculpture", fundamental: "Form in three dimensions", artefact: "A finished sculpture" },
  { slug: "collage", name: "collage", fundamental: "Composition and contrast", artefact: "A finished collage series" },
];

function learnMedium(m: Medium): TemplateSpec {
  return {
    key: `creative-${m.slug}-learn`,
    title: `Learn ${m.name}`,
    summary: `Build real skill in ${m.name}, starting with the fundamental most beginners skip: ${m.fundamental.toLowerCase()}.`,
    category: "creative",
    difficulty: m.hard ? 4 : 3,
    weeks: m.hard ? 36 : 24,
    tags: [m.slug.replace(/-/g, " "), m.name, "creative", "art", "skill"],
    skills: [m.fundamental, "Deliberate practice", "Studying reference and masters", "Finishing work", "Feedback and revision"],
    milestones: ["Fundamentals understood", "Daily or weekly practice habit", "First piece finished start to end", m.artefact],
  };
}

const generated = MEDIA.map(learnMedium);

const extras: TemplateSpec[] = [
  {
    key: "creative-write-novel",
    title: "Write a novel",
    summary: "Get a complete first draft finished — the hardest and most skipped part of writing a book.",
    category: "creative",
    difficulty: 4,
    weeks: 52,
    tags: ["writing", "novel", "fiction", "book", "draft"],
    skills: ["Story structure", "Character development", "Daily writing habit", "Scene craft", "Revision"],
    milestones: ["Premise and outline settled", "25,000 words written", "50,000 words written", "First draft complete", "Second draft complete"],
    metric: { name: "Word count", target: 80000, unit: "words" },
  },
  {
    key: "creative-write-short-stories",
    title: "Write and finish ten short stories",
    summary: "Volume over perfection — the fastest way to actually improve at fiction.",
    category: "creative",
    difficulty: 3,
    weeks: 40,
    tags: ["writing", "short story", "fiction", "craft"],
    skills: ["Story shape", "Character in brief", "Editing", "Submitting work"],
    milestones: ["First story finished", "Three stories finished", "Six stories finished", "Ten stories finished"],
    metric: { name: "Finished stories", target: 10, unit: "stories" },
  },
  {
    key: "creative-publish-book",
    title: "Publish a book",
    summary: "Take a finished manuscript through editing, design and publication to actual readers.",
    category: "project",
    difficulty: 4,
    weeks: 52,
    tags: ["publishing", "book", "self-publishing", "author"],
    skills: ["Manuscript editing", "Cover and interior design", "Publishing route selection", "Launch and marketing"],
    milestones: ["Manuscript professionally edited", "Cover and layout finished", "Published and listed", "First fifty copies sold"],
  },
  {
    key: "creative-poetry",
    title: "Write poetry seriously",
    summary: "Develop a real poetic practice, from imitation exercises to a body of your own work.",
    category: "creative",
    difficulty: 3,
    weeks: 36,
    tags: ["poetry", "writing", "verse", "craft"],
    skills: ["Reading widely", "Form and constraint", "Image and sound", "Revision", "Sharing and submitting"],
    milestones: ["Reading habit established", "Twenty drafts written", "Ten poems revised to finished", "First submission sent"],
  },
  {
    key: "creative-screenplay",
    title: "Write a feature screenplay",
    summary: "A complete, properly formatted feature script from logline to final draft.",
    category: "creative",
    difficulty: 4,
    weeks: 40,
    tags: ["screenwriting", "film", "script", "story"],
    skills: ["Three-act structure", "Scene writing", "Dialogue", "Formatting", "Revision"],
    milestones: ["Logline and outline locked", "Act one drafted", "First draft complete", "Rewrite complete"],
  },
  {
    key: "creative-blog",
    title: "Start and sustain a blog",
    summary: "Publish consistently for long enough that it compounds into an audience.",
    category: "creative",
    difficulty: 2,
    weeks: 32,
    tags: ["blogging", "writing", "publishing", "audience"],
    skills: ["Topic selection", "Writing to a schedule", "Editing", "Distribution"],
    milestones: ["Blog live with first post", "Five posts published", "Fifteen posts published", "Consistent readership"],
    metric: { name: "Posts published", target: 25, unit: "posts" },
  },
  {
    key: "creative-podcast",
    title: "Launch a podcast",
    summary: "From concept and gear to a published season people actually finish.",
    category: "project",
    difficulty: 3,
    weeks: 28,
    tags: ["podcast", "audio", "interview", "publishing"],
    skills: ["Format and concept", "Recording and audio quality", "Interviewing", "Editing", "Publishing and growth"],
    milestones: ["Concept and format set", "Pilot episode recorded", "First three episodes published", "Full season released"],
  },
  {
    key: "creative-youtube",
    title: "Build a YouTube channel",
    summary: "Learn the whole loop — idea, script, shoot, edit, thumbnail — and publish consistently.",
    category: "creative",
    difficulty: 3,
    weeks: 40,
    tags: ["youtube", "video", "content", "audience"],
    skills: ["Idea and packaging", "Scripting", "Filming", "Editing", "Analytics and iteration"],
    milestones: ["First video published", "Ten videos published", "Consistent upload schedule", "First 1,000 subscribers"],
  },
  {
    key: "creative-daily-art-habit",
    title: "Make art every day for 100 days",
    summary: "Quantity builds skill and kills perfectionism — a hundred small finished pieces.",
    category: "habit",
    difficulty: 2,
    weeks: 15,
    tags: ["daily", "habit", "art", "100 days", "practice"],
    skills: ["Small scoping", "Daily trigger", "Publishing without polish"],
    milestones: ["Day 10", "Day 30", "Day 60", "Day 100"],
    metric: { name: "Consecutive days", target: 100, unit: "days" },
  },
  {
    key: "creative-find-style",
    title: "Develop your own artistic voice",
    summary: "Move past imitation into work that is recognisably yours.",
    category: "creative",
    difficulty: 4,
    weeks: 44,
    tags: ["style", "voice", "identity", "art"],
    skills: ["Influence mapping", "Deliberate experimentation", "Self-critique", "Body-of-work thinking"],
    milestones: ["Influences identified honestly", "Twenty experiments made", "Recurring choices identified", "Cohesive body of work"],
  },
  {
    key: "creative-exhibition",
    title: "Exhibit or sell your work",
    summary: "Get your work in front of an audience — a show, a market stall or an online store.",
    category: "project",
    difficulty: 3,
    weeks: 32,
    tags: ["exhibition", "selling", "gallery", "market"],
    skills: ["Body of work curation", "Presentation and framing", "Pricing", "Outreach and applications"],
    milestones: ["Ten finished pieces ready", "Presentation sorted", "Venue or platform secured", "First piece sold or shown"],
  },
  {
    key: "creative-tattoo-design",
    title: "Learn tattoo design and flash",
    summary: "The drawing skills specific to tattooing — bold line, readability and longevity.",
    category: "creative",
    difficulty: 4,
    weeks: 40,
    tags: ["tattoo", "flash", "design", "linework"],
    skills: ["Bold linework", "Readability at size", "Flash sheet composition", "Style study", "Client brief translation"],
    milestones: ["Linework consistent", "First flash sheet complete", "Five flash sheets", "Portfolio ready"],
  },
  {
    key: "creative-interior-design",
    title: "Design a room properly",
    summary: "Apply real design principles to a space instead of buying things and hoping.",
    category: "creative",
    difficulty: 2,
    weeks: 14,
    tags: ["interior design", "home", "space", "styling"],
    skills: ["Space planning", "Colour and light", "Material and texture", "Budgeting and sourcing"],
    milestones: ["Brief and budget set", "Plan and mood board finished", "Key pieces sourced", "Room finished"],
  },
];

export const creative: TemplateDomain = {
  key: "creative",
  label: "Art & creative",
  blurb: "Drawing, painting, photography, writing, film and finding your own voice.",
  templates: [...generated, ...extras],
};
