import type { TemplateDomain } from "../types";

export const fitness: TemplateDomain = {
  key: "fitness",
  label: "Fitness & strength",
  blurb: "Training, body composition, mobility and everyday physical capability.",
  templates: [
    {
      key: "fitness-run-5k",
      title: "Run 5K without stopping",
      summary: "Go from little or no running to covering five kilometres continuously.",
      category: "fitness",
      difficulty: 2,
      weeks: 10,
      tags: ["running", "cardio", "beginner", "couch to 5k"],
      skills: ["Aerobic base", "Running form", "Pacing", "Recovery habits"],
      milestones: ["Run 1K continuously", "Run 2K continuously", "Run 3.5K continuously", "Complete a full 5K"],
      metric: { name: "Longest continuous run", target: 5, unit: "km" },
    },
    {
      key: "fitness-run-10k",
      title: "Run a sub-50 minute 10K",
      summary: "Build the endurance and pace discipline to break fifty minutes over ten kilometres.",
      category: "fitness",
      difficulty: 3,
      weeks: 16,
      tags: ["running", "10k", "endurance", "pace"],
      skills: ["Aerobic base", "Tempo running", "Interval work", "Race pacing", "Recovery habits"],
      milestones: ["Comfortable 10K distance", "Sustain tempo pace for 20 min", "Complete a 55-min time trial", "Break 50 minutes"],
      metric: { name: "10K time", target: 50, unit: "min" },
    },
    {
      key: "fitness-half-marathon",
      title: "Finish a half marathon",
      summary: "Train safely from a running base to completing 21.1 kilometres.",
      category: "fitness",
      difficulty: 3,
      weeks: 18,
      tags: ["running", "half marathon", "endurance", "21k"],
      skills: ["Long-run endurance", "Weekly mileage build", "Fuelling strategy", "Injury prevention", "Race-day planning"],
      milestones: ["Run 8K comfortably", "Complete a 12K long run", "Complete an 18K long run", "Finish the half marathon"],
      metric: { name: "Longest run", target: 21.1, unit: "km" },
    },
    {
      key: "fitness-marathon",
      title: "Finish a marathon",
      summary: "A full training block from a half-marathon base to 42.2 kilometres.",
      category: "fitness",
      difficulty: 4,
      weeks: 24,
      tags: ["running", "marathon", "endurance", "42k"],
      skills: ["Long-run endurance", "Mileage periodisation", "Fuelling strategy", "Strength & injury prevention", "Taper and race execution"],
      milestones: ["Hold a 25 km/week base", "Complete a 21K long run", "Complete a 32K long run", "Taper week complete", "Finish the marathon"],
      metric: { name: "Longest run", target: 42.2, unit: "km" },
    },
    {
      key: "fitness-first-pullup",
      title: "Do your first pull-up",
      summary: "Build the pulling strength to complete one clean, unassisted pull-up.",
      category: "fitness",
      difficulty: 2,
      weeks: 12,
      tags: ["calisthenics", "strength", "pull-up", "bodyweight"],
      skills: ["Scapular control", "Assisted pulling volume", "Eccentric strength", "Grip strength"],
      milestones: ["Hold a 30-second dead hang", "10 controlled band-assisted reps", "5-second slow negative", "One unassisted pull-up"],
      metric: { name: "Unassisted pull-ups", target: 1, unit: "reps" },
    },
    {
      key: "fitness-ten-pullups",
      title: "Do ten consecutive pull-ups",
      summary: "Progress from a single rep to ten clean unbroken pull-ups.",
      category: "fitness",
      difficulty: 3,
      weeks: 20,
      tags: ["calisthenics", "strength", "pull-up", "bodyweight"],
      skills: ["Pulling volume", "Progressive overload", "Grip endurance", "Core bracing", "Recovery habits"],
      milestones: ["3 consecutive reps", "5 consecutive reps", "8 consecutive reps", "10 consecutive reps"],
      metric: { name: "Consecutive pull-ups", target: 10, unit: "reps" },
    },
    {
      key: "fitness-bodyweight-bench",
      title: "Bench press your bodyweight",
      summary: "Build pressing strength to bench one times bodyweight for a single rep.",
      category: "fitness",
      difficulty: 3,
      weeks: 24,
      tags: ["strength", "powerlifting", "bench press", "gym"],
      skills: ["Bench technique", "Progressive overload", "Accessory pressing", "Nutrition for strength", "Deload management"],
      milestones: ["Technique dialled in with light load", "70% bodyweight for 5 reps", "90% bodyweight single", "Bodyweight bench press"],
    },
    {
      key: "fitness-squat-2x",
      title: "Squat double bodyweight",
      summary: "A long strength block toward a two-times-bodyweight back squat.",
      category: "fitness",
      difficulty: 4,
      weeks: 52,
      tags: ["strength", "powerlifting", "squat", "gym"],
      skills: ["Squat technique", "Progressive overload", "Posterior chain accessories", "Mobility", "Nutrition for strength", "Deload management"],
      milestones: ["Depth and bracing consistent", "1.2x bodyweight single", "1.5x bodyweight single", "1.8x bodyweight single", "2x bodyweight squat"],
    },
    {
      key: "fitness-gym-habit",
      title: "Build a consistent gym habit",
      summary: "Train three times a week for three months without relying on motivation.",
      category: "habit",
      difficulty: 2,
      weeks: 12,
      tags: ["gym", "habit", "consistency", "routine"],
      skills: ["Session planning", "Scheduling & triggers", "Basic lift technique", "Progress tracking"],
      milestones: ["Two weeks at 3 sessions", "One month unbroken", "Two months unbroken", "Three months unbroken"],
      metric: { name: "Sessions completed", target: 36, unit: "sessions" },
    },
    {
      key: "fitness-lose-fat",
      title: "Lose body fat sustainably",
      summary: "A gradual, health-first cut that protects muscle and stays maintainable.",
      category: "fitness",
      difficulty: 3,
      weeks: 20,
      tags: ["weight loss", "nutrition", "body composition", "cutting"],
      skills: ["Calorie awareness", "Protein and food quality", "Resistance training", "Daily movement", "Sleep and stress"],
      milestones: ["Baseline measurements logged", "Four weeks of consistent tracking", "Halfway checkpoint", "Target reached and stabilised"],
    },
    {
      key: "fitness-gain-muscle",
      title: "Put on lean muscle",
      summary: "A structured hypertrophy block with progressive overload and enough food to grow.",
      category: "fitness",
      difficulty: 3,
      weeks: 24,
      tags: ["muscle", "hypertrophy", "bulking", "gym"],
      skills: ["Hypertrophy programming", "Compound lift technique", "Eating for growth", "Sleep and recovery", "Progress tracking"],
      milestones: ["Programme and baseline set", "Consistent 4 sessions/week for a month", "Measurable strength increase", "Visible size change and target reached"],
    },
    {
      key: "fitness-touch-toes",
      title: "Touch your toes",
      summary: "A gentle mobility programme to reach comfortable forward flexion.",
      category: "fitness",
      difficulty: 1,
      weeks: 8,
      tags: ["mobility", "flexibility", "stretching", "hamstrings"],
      skills: ["Hamstring mobility", "Hip hinge pattern", "Daily stretching habit"],
      milestones: ["Daily stretching established", "Fingertips to shins", "Fingertips to toes"],
    },
    {
      key: "fitness-splits",
      title: "Achieve the front splits",
      summary: "Progressive flexibility training toward a full front split.",
      category: "fitness",
      difficulty: 3,
      weeks: 36,
      tags: ["flexibility", "mobility", "splits", "stretching"],
      skills: ["Hamstring mobility", "Hip flexor mobility", "Active flexibility strength", "Consistent daily practice"],
      milestones: ["Daily practice established", "Halfway depth held comfortably", "Near-full split with support", "Full front split"],
    },
    {
      key: "fitness-handstand",
      title: "Hold a freestanding handstand",
      summary: "Build the shoulder strength and balance for a thirty-second free handstand.",
      category: "fitness",
      difficulty: 4,
      weeks: 36,
      tags: ["calisthenics", "handstand", "balance", "gymnastics"],
      skills: ["Wrist and shoulder prep", "Wall handstand endurance", "Balance and bailing", "Line and body tension", "Daily practice consistency"],
      milestones: ["60-second wall hold", "Consistent kick-up to balance", "10-second free hold", "30-second free hold"],
      metric: { name: "Free hold", target: 30, unit: "sec" },
    },
    {
      key: "fitness-swim-freestyle",
      title: "Swim 1km freestyle continuously",
      summary: "Learn efficient front crawl and build to a continuous kilometre.",
      category: "fitness",
      difficulty: 3,
      weeks: 16,
      tags: ["swimming", "freestyle", "endurance", "technique"],
      skills: ["Breathing rhythm", "Stroke technique", "Kick efficiency", "Endurance sets"],
      milestones: ["Comfortable 100m", "Continuous 300m", "Continuous 600m", "Continuous 1km"],
      metric: { name: "Continuous distance", target: 1000, unit: "m" },
    },
    {
      key: "fitness-cycle-century",
      title: "Ride a 100km bike ride",
      summary: "Build cycling endurance and fuelling for a full century ride.",
      category: "fitness",
      difficulty: 3,
      weeks: 20,
      tags: ["cycling", "endurance", "century", "bike"],
      skills: ["Aerobic endurance", "Bike handling", "Fuelling and hydration", "Cadence and efficiency"],
      milestones: ["Comfortable 30km ride", "Complete a 50km ride", "Complete a 75km ride", "Complete 100km"],
      metric: { name: "Longest ride", target: 100, unit: "km" },
    },
    {
      key: "fitness-posture",
      title: "Fix desk-work posture and back pain",
      summary: "Reduce everyday stiffness with targeted mobility and workstation changes.",
      category: "fitness",
      difficulty: 2,
      weeks: 12,
      tags: ["posture", "back pain", "mobility", "desk"],
      skills: ["Thoracic mobility", "Core and glute strength", "Workstation setup", "Movement breaks"],
      milestones: ["Workstation adjusted", "Daily mobility routine established", "Noticeable stiffness reduction", "Pain-free typical workday"],
    },
    {
      key: "fitness-10k-steps",
      title: "Walk 10,000 steps a day",
      summary: "Raise daily movement to ten thousand steps and keep it there.",
      category: "habit",
      difficulty: 1,
      weeks: 8,
      tags: ["walking", "steps", "habit", "daily movement"],
      skills: ["Step tracking", "Routine walk slots", "Obstacle planning"],
      milestones: ["Baseline measured", "7,000 steps daily for a week", "10,000 steps daily for two weeks", "10,000 steps sustained for a month"],
      metric: { name: "Daily steps", target: 10000, unit: "steps" },
    },
    {
      key: "fitness-hyrox",
      title: "Complete a HYROX or obstacle race",
      summary: "Combine running endurance with functional strength for a hybrid fitness race.",
      category: "sport",
      difficulty: 4,
      weeks: 24,
      tags: ["hyrox", "obstacle race", "hybrid", "conditioning"],
      skills: ["Running endurance", "Functional strength", "Compromised-running practice", "Station technique", "Race pacing"],
      milestones: ["Baseline fitness test", "Complete half-distance simulation", "Complete full simulation", "Race day finished"],
    },
    {
      key: "fitness-return-after-injury",
      title: "Return to training after an injury",
      summary: "A careful, staged comeback that rebuilds capacity without re-injury.",
      category: "fitness",
      difficulty: 3,
      weeks: 16,
      tags: ["injury", "rehab", "recovery", "return to sport"],
      skills: ["Pain and load monitoring", "Rehab exercise adherence", "Gradual load progression", "Confidence rebuilding"],
      milestones: ["Cleared to begin loading", "Pain-free daily movement", "Back to 50% previous load", "Back to full training"],
    },
  ],
};
