import type { TemplateDomain, TemplateSpec } from "../types";

interface Cuisine {
  slug: string;
  name: string;
  /** The technique that unlocks the cuisine. */
  technique: string;
  /** A dish that proves you can cook it. */
  signature: string;
}

const CUISINES: Cuisine[] = [
  { slug: "italian", name: "Italian", technique: "Pasta and sauce emulsification", signature: "Fresh pasta with a proper sauce" },
  { slug: "french", name: "French", technique: "Mother sauces and knife work", signature: "A classic braise and pan sauce" },
  { slug: "japanese", name: "Japanese", technique: "Rice, dashi and precision", signature: "Dashi-based soup and perfect rice" },
  { slug: "chinese", name: "Chinese", technique: "Wok heat control", signature: "A stir-fry with real wok hei" },
  { slug: "thai", name: "Thai", technique: "Balancing sour, sweet, salty and hot", signature: "A curry from a paste you made" },
  { slug: "indian", name: "Indian", technique: "Layering spices and tempering", signature: "A curry built from whole spices" },
  { slug: "mexican", name: "Mexican", technique: "Chillies, masa and salsas", signature: "Handmade tortillas and a salsa" },
  { slug: "korean", name: "Korean", technique: "Fermentation and banchan", signature: "Homemade kimchi and a rice dish" },
  { slug: "vietnamese", name: "Vietnamese", technique: "Broth clarity and fresh herbs", signature: "A proper pho broth" },
  { slug: "spanish", name: "Spanish", technique: "Sofrito and rice control", signature: "Paella with a good socarrat" },
  { slug: "greek", name: "Greek", technique: "Olive oil, lemon and slow roasting", signature: "A slow-roasted lamb dish" },
  { slug: "turkish", name: "Turkish", technique: "Grilling and yoghurt sauces", signature: "Kebabs with proper flatbread" },
  { slug: "lebanese", name: "Lebanese", technique: "Mezze balance and spicing", signature: "A full mezze spread" },
  { slug: "moroccan", name: "Moroccan", technique: "Slow tagine cooking and spice blends", signature: "A tagine cooked from scratch" },
  { slug: "ethiopian", name: "Ethiopian", technique: "Berbere and injera fermentation", signature: "Injera with two stews" },
  { slug: "persian", name: "Persian", technique: "Rice technique and herb balance", signature: "Rice with a perfect tahdig" },
  { slug: "caribbean", name: "Caribbean", technique: "Jerk seasoning and slow grilling", signature: "Jerk chicken done properly" },
  { slug: "peruvian", name: "Peruvian", technique: "Citrus curing and ají pastes", signature: "Ceviche with fresh leche de tigre" },
  { slug: "brazilian", name: "Brazilian", technique: "Slow stews and grilling", signature: "Feijoada from scratch" },
  { slug: "german", name: "German", technique: "Curing, braising and baking", signature: "A braise with homemade dumplings" },
  { slug: "polish", name: "Polish", technique: "Dumpling making and pickling", signature: "Handmade pierogi" },
  { slug: "malaysian", name: "Malaysian", technique: "Rempah paste building", signature: "A curry from a pounded rempah" },
  { slug: "filipino", name: "Filipino", technique: "Vinegar braising and balance", signature: "Adobo cooked properly" },
];

function cookCuisine(c: Cuisine): TemplateSpec {
  return {
    key: `food-cook-${c.slug}`,
    title: `Learn to cook ${c.name} food`,
    summary: `Cook ${c.name} properly rather than approximately — the key is ${c.technique.toLowerCase()}.`,
    category: "general",
    difficulty: 3,
    weeks: 20,
    tags: [c.slug, c.name.toLowerCase(), "cooking", "food", "cuisine"],
    skills: ["Core ingredients and pantry", c.technique, "Knife and prep work", "Recipe repertoire", "Tasting and adjusting"],
    milestones: ["Pantry stocked and basics understood", "Three dishes cooked well", c.signature, "Cook a full meal for guests"],
  };
}

const generated = CUISINES.map(cookCuisine);

const extras: TemplateSpec[] = [
  {
    key: "food-learn-to-cook",
    title: "Learn to cook from scratch",
    summary: "Go from takeaway and packets to cooking real food you actually want to eat.",
    category: "general",
    difficulty: 2,
    weeks: 16,
    tags: ["cooking", "beginner", "basics", "home cooking"],
    skills: ["Knife skills", "Heat control", "Seasoning and tasting", "Ten reliable recipes", "Shopping and planning"],
    milestones: ["Knife skills safe and quick", "Five meals cooked unaided", "Cook without a recipe", "Cook for other people"],
  },
  {
    key: "food-knife-skills",
    title: "Get genuinely good with a knife",
    summary: "Speed, safety and consistency — the single highest-leverage cooking skill.",
    category: "general",
    difficulty: 2,
    weeks: 8,
    tags: ["knife skills", "prep", "technique", "cooking"],
    skills: ["Grip and safety", "Core cuts", "Speed with control", "Sharpening"],
    milestones: ["Grip and posture correct", "Dice an onion cleanly", "Prep a full meal quickly", "Sharpen your own knives"],
  },
  {
    key: "food-meal-prep",
    title: "Meal prep every week",
    summary: "A repeatable weekly system that removes the daily decision entirely.",
    category: "habit",
    difficulty: 2,
    weeks: 12,
    tags: ["meal prep", "batch cooking", "planning", "habit"],
    skills: ["Menu planning", "Batch cooking", "Storage and food safety", "Shopping efficiency"],
    milestones: ["First prep session done", "Four weeks in a row", "Eight weeks in a row", "System running without thinking"],
  },
  {
    key: "food-bake-bread",
    title: "Bake really good bread",
    summary: "Understand dough well enough to bake consistently rather than hopefully.",
    category: "general",
    difficulty: 3,
    weeks: 16,
    tags: ["bread", "baking", "dough", "yeast"],
    skills: ["Dough hydration and handling", "Fermentation timing", "Shaping", "Baking and crust"],
    milestones: ["First loaf baked", "Consistent crumb", "Shaping is reliable", "Bread better than the shop's"],
  },
  {
    key: "food-sourdough",
    title: "Master sourdough",
    summary: "Keep a starter alive and bake genuinely good naturally-leavened bread.",
    category: "general",
    difficulty: 4,
    weeks: 24,
    tags: ["sourdough", "bread", "fermentation", "starter"],
    skills: ["Starter maintenance", "Bulk fermentation reading", "Shaping and tension", "Scoring and baking", "Troubleshooting"],
    milestones: ["Starter active and predictable", "First decent loaf", "Consistent open crumb", "Bake reliably to a schedule"],
  },
  {
    key: "food-pastry",
    title: "Learn pastry and baking",
    summary: "The precision side of the kitchen — laminated doughs, custards and proper cakes.",
    category: "general",
    difficulty: 4,
    weeks: 28,
    tags: ["pastry", "baking", "dessert", "patisserie"],
    skills: ["Measurement precision", "Pastry doughs", "Lamination", "Custards and creams", "Finishing and decoration"],
    milestones: ["Shortcrust and choux working", "Laminated dough successful", "A layered dessert completed", "A show-quality centrepiece"],
  },
  {
    key: "food-fermentation",
    title: "Learn fermentation",
    summary: "Kimchi, kraut, kefir, hot sauce — safe, repeatable fermentation at home.",
    category: "general",
    difficulty: 3,
    weeks: 20,
    tags: ["fermentation", "kimchi", "pickling", "preserving"],
    skills: ["Salt ratios and safety", "Vegetable ferments", "Dairy ferments", "Troubleshooting and storage"],
    milestones: ["First successful ferment", "Three ferments running", "Adjusted a recipe to taste", "Ferments part of normal cooking"],
  },
  {
    key: "food-butchery",
    title: "Learn home butchery",
    summary: "Break down whole birds and primal cuts — better meat, far cheaper.",
    category: "general",
    difficulty: 3,
    weeks: 14,
    tags: ["butchery", "meat", "knife", "cooking"],
    skills: ["Knife handling and safety", "Poultry breakdown", "Primal cuts", "Using the whole animal"],
    milestones: ["Break down a chicken", "Debone confidently", "Break down a larger primal", "Nothing wasted"],
  },
  {
    key: "food-cocktails",
    title: "Make proper cocktails",
    summary: "Understand balance and technique instead of following recipes blindly.",
    category: "general",
    difficulty: 2,
    weeks: 12,
    tags: ["cocktails", "bartending", "drinks", "mixology"],
    skills: ["Balance and ratios", "Shaking and stirring technique", "Ice and dilution", "Syrups and garnishes"],
    milestones: ["Five classics made well", "Adjust a drink to taste", "Make syrups from scratch", "Host and serve for guests"],
  },
  {
    key: "food-coffee",
    title: "Make café-quality coffee at home",
    summary: "Dial in grind, dose and extraction until it is consistently good.",
    category: "general",
    difficulty: 2,
    weeks: 10,
    tags: ["coffee", "espresso", "brewing", "barista"],
    skills: ["Grind and dose control", "Extraction and tasting", "Milk texturing", "Equipment maintenance"],
    milestones: ["Consistent brew method", "Dial in a new bean unaided", "Pour steamed milk well", "Consistently better than the café"],
  },
  {
    key: "food-wine",
    title: "Learn about wine properly",
    summary: "Taste with structure and vocabulary rather than guessing from the label.",
    category: "general",
    difficulty: 3,
    weeks: 24,
    tags: ["wine", "tasting", "sommelier", "drinks"],
    skills: ["Structured tasting", "Grape varieties", "Regions and styles", "Food pairing", "Blind tasting practice"],
    milestones: ["Tasting vocabulary usable", "Identify major varieties", "Pair confidently with food", "Identify a wine blind"],
  },
  {
    key: "food-vegetarian-transition",
    title: "Go vegetarian or vegan properly",
    summary: "Make the switch nutritionally sound and genuinely enjoyable rather than restrictive.",
    category: "habit",
    difficulty: 2,
    weeks: 16,
    tags: ["vegetarian", "vegan", "plant-based", "diet"],
    skills: ["Protein and nutrient planning", "Plant-based cooking repertoire", "Shopping and substitutions", "Eating out and social situations"],
    milestones: ["Ten meals you genuinely like", "Nutrition gaps covered", "One month sustained", "Three months sustained"],
  },
  {
    key: "food-reduce-waste",
    title: "Cut your food waste to almost nothing",
    summary: "Plan, store and use what you buy — better for money and for the bin.",
    category: "habit",
    difficulty: 2,
    weeks: 12,
    tags: ["food waste", "sustainability", "planning", "budget"],
    skills: ["Inventory awareness", "Storage technique", "Using leftovers and scraps", "Realistic planning"],
    milestones: ["Baseline waste measured", "Weekly planning running", "Waste halved", "Waste near zero"],
  },
  {
    key: "food-host-dinner",
    title: "Host a dinner party without panicking",
    summary: "Menu design and timing so you can actually enjoy your own dinner.",
    category: "general",
    difficulty: 3,
    weeks: 12,
    tags: ["hosting", "dinner party", "entertaining", "cooking"],
    skills: ["Menu design", "Prep-ahead planning", "Kitchen timing", "Hosting flow"],
    milestones: ["Menu planned with prep-ahead", "Cook for two guests", "Cook for six guests", "Host relaxed and on time"],
  },
];

export const food: TemplateDomain = {
  key: "food",
  label: "Food & cooking",
  blurb: "Cooking well, baking, cuisines, drinks and eating better.",
  templates: [...generated, ...extras],
};
