import type { TemplateDomain, TemplateSpec } from "../types";

interface Fear {
  slug: string;
  name: string;
  /** The graded step that makes exposure work for this specific fear. */
  ladder: string;
  weeks: number;
}

const FEARS: Fear[] = [
  { slug: "public-speaking", name: "public speaking", ladder: "Speaking to progressively larger groups", weeks: 24 },
  { slug: "heights", name: "heights", ladder: "Progressively higher, safe vantage points", weeks: 20 },
  { slug: "water", name: "deep water", ladder: "Progressive depth with support", weeks: 24 },
  { slug: "spiders", name: "spiders", ladder: "Images, then distance, then proximity", weeks: 16 },
  { slug: "needles", name: "needles and blood", ladder: "Images, then clinical settings, then procedures", weeks: 16 },
  { slug: "driving", name: "driving", ladder: "Quiet roads, then busier ones, then motorways", weeks: 24 },
  { slug: "dogs", name: "dogs", ladder: "Distance, then calm dogs, then proximity", weeks: 16 },
  { slug: "confined-spaces", name: "confined spaces", ladder: "Progressively smaller or busier spaces", weeks: 20 },
  { slug: "rejection", name: "rejection", ladder: "Deliberately asking for things likely to be refused", weeks: 20 },
  { slug: "failure", name: "failure", ladder: "Attempting things you might visibly not manage", weeks: 24 },
];

const fearTemplates: TemplateSpec[] = FEARS.map((f) => ({
  key: `growth-overcome-${f.slug}`,
  title: `Overcome your fear of ${f.name}`,
  summary: `Graded, repeated exposure — the approach with the strongest evidence behind it. ${f.ladder} is the shape of the work.`,
  category: "personal_development",
  difficulty: 3,
  weeks: f.weeks,
  tags: [f.slug.replace(/-/g, " "), "fear", "anxiety", "exposure", "confidence"],
  skills: ["Fear hierarchy", "Anxiety regulation", "Graded exposure", "Dropping safety behaviours", "Support where needed"],
  milestones: ["Hierarchy written", "Easiest steps repeated until dull", "A genuinely hard step completed", `${f.name.charAt(0).toUpperCase() + f.name.slice(1)} no longer limits you`],
}));

const extras: TemplateSpec[] = [
  {
    key: "growth-build-discipline",
    title: "Build real self-discipline",
    summary: "Systems, environment and identity — not white-knuckling it harder.",
    category: "personal_development",
    difficulty: 4,
    weeks: 32,
    tags: ["discipline", "willpower", "consistency", "habits"],
    skills: ["Environment design", "Small non-negotiables", "Identity-based framing", "Recovering from lapses"],
    milestones: ["One non-negotiable held for a month", "Three habits stable", "Survived a disrupted period", "Discipline feels normal, not heroic"],
  },
  {
    key: "growth-build-any-habit",
    title: "Build a habit that actually sticks",
    summary: "One habit, properly installed, using what is actually known about habit formation.",
    category: "habit",
    difficulty: 2,
    weeks: 16,
    tags: ["habit", "routine", "consistency", "behaviour"],
    skills: ["Making it small enough", "Anchoring to an existing routine", "Making it obvious", "Tracking", "Never missing twice"],
    milestones: ["Habit defined tiny and specific", "Two weeks unbroken", "Six weeks unbroken", "Automatic"],
  },
  {
    key: "growth-break-a-habit",
    title: "Break a habit you want rid of",
    summary: "Remove cues, add friction and replace the behaviour rather than relying on resolve.",
    category: "habit",
    difficulty: 3,
    weeks: 20,
    tags: ["habit", "quit", "breaking", "behaviour"],
    skills: ["Cue identification", "Friction and removal", "Replacement behaviour", "Lapse recovery"],
    milestones: ["Cues identified", "Environment changed", "One month clear", "Three months clear"],
  },
  {
    key: "growth-morning-routine",
    title: "Build a morning routine that works",
    summary: "A short, realistic routine you keep, rather than an aspirational five-hour one you abandon.",
    category: "habit",
    difficulty: 2,
    weeks: 12,
    tags: ["morning", "routine", "habit", "start"],
    skills: ["Realistic scoping", "Evening preparation", "Consistent wake time", "Protecting it"],
    milestones: ["Routine designed and short", "One week consistent", "One month consistent", "Automatic on most days"],
  },
  {
    key: "growth-evening-routine",
    title: "Build a proper evening wind-down",
    summary: "The routine that actually determines how your mornings go.",
    category: "habit",
    difficulty: 2,
    weeks: 10,
    tags: ["evening", "routine", "wind down", "sleep"],
    skills: ["Screen cut-off", "Preparation for tomorrow", "Wind-down activity", "Consistent timing"],
    milestones: ["Routine designed", "One week consistent", "Noticeably better sleep", "Automatic"],
  },
  {
    key: "growth-self-awareness",
    title: "Understand yourself better",
    summary: "Structured reflection to see your own patterns rather than repeating them blindly.",
    category: "personal_development",
    difficulty: 3,
    weeks: 28,
    tags: ["self-awareness", "reflection", "patterns", "growth"],
    skills: ["Regular structured reflection", "Seeking honest feedback", "Noticing triggers", "Acting on what you find"],
    milestones: ["Reflection routine running", "Feedback sought from three people", "A real pattern identified", "Behaviour changed because of it"],
  },
  {
    key: "growth-values",
    title: "Work out what you actually value",
    summary: "Get clear on your priorities so decisions stop being exhausting.",
    category: "personal_development",
    difficulty: 3,
    weeks: 16,
    tags: ["values", "priorities", "clarity", "purpose"],
    skills: ["Structured values exercises", "Testing against real decisions", "Resolving conflicts between values", "Living accordingly"],
    milestones: ["First draft written", "Tested against real choices", "Refined and honest", "Used to make a hard decision"],
  },
  {
    key: "growth-life-direction",
    title: "Work out what you want to do with your life",
    summary: "Structured exploration instead of waiting for clarity to arrive on its own.",
    category: "personal_development",
    difficulty: 4,
    weeks: 36,
    tags: ["purpose", "direction", "career", "meaning"],
    skills: ["Honest self-assessment", "Structured exploration", "Small experiments", "Talking to people who do it", "Deciding without certainty"],
    milestones: ["Options generated widely", "Three explored properly", "One tested in practice", "A direction chosen and started"],
  },
  {
    key: "growth-say-no",
    title: "Stop over-committing",
    summary: "Protect your time by declining more, earlier, and without elaborate excuses.",
    category: "habit",
    difficulty: 3,
    weeks: 20,
    tags: ["overcommitment", "no", "time", "boundaries"],
    skills: ["Noticing the reflex to agree", "Buying time before answering", "Clear brief refusals", "Auditing existing commitments"],
    milestones: ["Commitments audited", "Three things declined", "Two existing commitments exited", "Calendar genuinely lighter"],
  },
  {
    key: "growth-perfectionism",
    title: "Get over perfectionism",
    summary: "Ship things at good enough and learn from what happens next.",
    category: "personal_development",
    difficulty: 4,
    weeks: 28,
    tags: ["perfectionism", "shipping", "done", "fear"],
    skills: ["Defining good enough in advance", "Time-boxing", "Shipping deliberately imperfect work", "Tolerating the discomfort"],
    milestones: ["Standards defined in advance", "Something shipped early on purpose", "Nothing terrible happened", "Shipping is the default"],
  },
  {
    key: "growth-imposter-syndrome",
    title: "Deal with imposter syndrome",
    summary: "Evidence and honest calibration rather than reassurance.",
    category: "personal_development",
    difficulty: 3,
    weeks: 24,
    tags: ["imposter syndrome", "confidence", "self-doubt", "work"],
    skills: ["Evidence logging", "Calibration against reality", "Talking about it", "Acting despite doubt"],
    milestones: ["Evidence log started", "Discussed with someone honestly", "Took an opportunity despite doubt", "Noticeably less gripped by it"],
  },
  {
    key: "growth-focus",
    title: "Rebuild your attention span",
    summary: "Attention is trainable, and it has usually been eroded rather than lost.",
    category: "habit",
    difficulty: 3,
    weeks: 20,
    tags: ["attention", "focus", "concentration", "distraction"],
    skills: ["Distraction removal", "Progressive focus blocks", "Boredom tolerance", "Single-tasking"],
    milestones: ["Distractions removed", "25 minutes focused reliably", "60 minutes focused", "Deep focus available on demand"],
  },
  {
    key: "growth-decision-making",
    title: "Make decisions better and faster",
    summary: "Frameworks that stop small decisions eating your week and big ones being made badly.",
    category: "personal_development",
    difficulty: 3,
    weeks: 20,
    tags: ["decisions", "judgement", "thinking", "clarity"],
    skills: ["Distinguishing reversible from irreversible", "Setting decision deadlines", "Seeking disconfirming evidence", "Reviewing past decisions"],
    milestones: ["Framework chosen", "Applied to small decisions", "Applied to a significant one", "Decisions no longer linger"],
  },
  {
    key: "growth-critical-thinking",
    title: "Think more clearly",
    summary: "Spot bad arguments, including your own, and reason more carefully.",
    category: "education",
    difficulty: 3,
    weeks: 24,
    tags: ["critical thinking", "logic", "reasoning", "bias"],
    skills: ["Argument structure", "Common fallacies", "Cognitive biases", "Evaluating evidence", "Changing your mind"],
    milestones: ["Fallacies recognisable", "Biases spotted in yourself", "Evidence evaluated properly", "Changed your mind on something real"],
  },
  {
    key: "growth-emotional-regulation",
    title: "Get better at handling your emotions",
    summary: "Feel things fully without being run by them.",
    category: "personal_development",
    difficulty: 4,
    weeks: 32,
    tags: ["emotions", "regulation", "anger", "self-control"],
    skills: ["Naming emotions precisely", "Noticing early physical signals", "Pause before reacting", "Recovery and repair"],
    milestones: ["Emotions named accurately", "Early signals noticed", "Paused instead of reacting", "Reactions no longer cause damage"],
  },
  {
    key: "growth-resilience",
    title: "Build resilience",
    summary: "Recover from setbacks faster, through preparation rather than toughness.",
    category: "personal_development",
    difficulty: 3,
    weeks: 32,
    tags: ["resilience", "setbacks", "recovery", "grit"],
    skills: ["Realistic expectations", "Support networks", "Meaning-making", "Physical foundations", "Recovery routines"],
    milestones: ["Foundations in place", "A setback handled well", "Recovery time noticeably shorter", "Setbacks no longer derail you"],
  },
  {
    key: "growth-optimism",
    title: "Change how you talk to yourself",
    summary: "Internal narration is a habit, and habits can be changed with practice.",
    category: "personal_development",
    difficulty: 3,
    weeks: 24,
    tags: ["self-talk", "mindset", "negativity", "cognition"],
    skills: ["Noticing the narration", "Testing accuracy", "Realistic reframing", "Repetition"],
    milestones: ["Patterns noticed and recorded", "Actively challenged", "Default tone shifting", "Noticeably kinder and more accurate"],
  },
  {
    key: "growth-comfort-zone",
    title: "Do one uncomfortable thing every week",
    summary: "A deliberate, repeatable practice for expanding what feels normal.",
    category: "habit",
    difficulty: 3,
    weeks: 26,
    tags: ["comfort zone", "courage", "growth", "challenge"],
    skills: ["Identifying real edges", "Scheduling discomfort", "Reflecting afterwards", "Escalating gradually"],
    milestones: ["Four weeks done", "Twelve weeks done", "A genuinely significant challenge taken", "Twenty-six weeks done"],
    metric: { name: "Weeks completed", target: 26, unit: "weeks" },
  },
  {
    key: "growth-mindfulness-daily",
    title: "Be more present in daily life",
    summary: "Mindfulness applied to ordinary moments rather than only on a cushion.",
    category: "habit",
    difficulty: 3,
    weeks: 24,
    tags: ["mindfulness", "presence", "awareness", "daily"],
    skills: ["Anchoring to the senses", "Single-tasking", "Noticing autopilot", "Informal practice"],
    milestones: ["Anchors chosen", "Noticing autopilot regularly", "Whole activities done attentively", "Presence is more common than absence"],
  },
  {
    key: "growth-life-audit",
    title: "Do a proper life audit",
    summary: "Honestly assess every area, then choose the two or three that actually need work.",
    category: "personal_development",
    difficulty: 2,
    weeks: 8,
    tags: ["audit", "review", "reflection", "planning"],
    skills: ["Honest area-by-area assessment", "Identifying leverage", "Prioritising ruthlessly", "Turning it into a plan"],
    milestones: ["All areas assessed honestly", "Priorities chosen", "Plan written", "First priority underway"],
  },
  {
    key: "growth-year-review",
    title: "Run a proper annual review",
    summary: "Look back honestly and set the next year deliberately rather than by default.",
    category: "personal_development",
    difficulty: 2,
    weeks: 6,
    tags: ["review", "annual", "reflection", "goals"],
    skills: ["Honest retrospection", "Pattern identification", "Realistic goal setting", "Turning goals into schedules"],
    milestones: ["Year reviewed honestly", "Patterns identified", "Next year's priorities set", "Scheduled into the calendar"],
  },
];

export const growth: TemplateDomain = {
  key: "growth",
  label: "Personal growth",
  blurb: "Habits, discipline, fears, clarity and the work of changing yourself.",
  templates: [...fearTemplates, ...extras],
};
