import type { TemplateDomain, TemplateSpec } from "../types";

export const life: TemplateDomain = {
  key: "life",
  label: "Home & life admin",
  blurb: "Organising your home, your paperwork and the practical machinery of adult life.",
  templates: [
    {
      key: "life-declutter-home",
      title: "Declutter your entire home",
      summary: "Room by room, decide what actually earns its space — and deal with the rest.",
      category: "project",
      difficulty: 3,
      weeks: 16,
      tags: ["declutter", "minimalism", "tidying", "home"],
      skills: ["Decision criteria", "Room-by-room sequencing", "Disposal and donation", "Preventing re-accumulation"],
      milestones: ["First room finished", "Half the home done", "Whole home decluttered", "Stayed decluttered for a month"],
    },
    {
      key: "life-organise-paperwork",
      title: "Get your paperwork under control",
      summary: "One system for documents, bills and records so nothing important goes missing again.",
      category: "project",
      difficulty: 2,
      weeks: 8,
      tags: ["paperwork", "documents", "filing", "admin"],
      skills: ["Sorting and triage", "Filing system design", "Digitisation", "Maintenance routine"],
      milestones: ["Backlog sorted", "System designed", "Everything filed", "Weekly maintenance running"],
    },
    {
      key: "life-cleaning-routine",
      title: "Build a cleaning routine that holds",
      summary: "Distribute cleaning across the week so it never becomes a weekend write-off.",
      category: "habit",
      difficulty: 2,
      weeks: 10,
      tags: ["cleaning", "routine", "home", "habit"],
      skills: ["Task distribution", "Daily resets", "Deep-clean scheduling", "Realistic standards"],
      milestones: ["Routine designed", "Two weeks followed", "One month sustained", "Home consistently presentable"],
    },
    {
      key: "life-move-house",
      title: "Move house without chaos",
      summary: "A sequenced plan covering everything from notice periods to the first night in the new place.",
      category: "project",
      difficulty: 3,
      weeks: 12,
      tags: ["moving", "relocation", "house", "admin"],
      skills: ["Timeline planning", "Packing system", "Address and utility changes", "Move-day logistics"],
      milestones: ["Timeline and checklist built", "Packing underway", "Move completed", "Fully unpacked and switched over"],
    },
    {
      key: "life-buy-first-home",
      title: "Buy your first home",
      summary: "Navigate the whole process from mortgage readiness to keys in hand.",
      category: "project",
      difficulty: 4,
      weeks: 52,
      tags: ["property", "mortgage", "first home", "buying"],
      skills: ["Mortgage readiness", "Market research", "Viewing and assessment", "Offer and negotiation", "Conveyancing process"],
      milestones: ["Mortgage in principle obtained", "Area and budget settled", "Offer accepted", "Completed and moved in"],
    },
    {
      key: "life-rent-first-place",
      title: "Move into your first place",
      summary: "Budget, viewings, contracts and everything you need to actually live there.",
      category: "project",
      difficulty: 2,
      weeks: 12,
      tags: ["renting", "first flat", "moving out", "independence"],
      skills: ["True cost budgeting", "Viewing and assessment", "Contract understanding", "Setting up utilities and essentials"],
      milestones: ["Budget calculated honestly", "Viewings done", "Contract signed", "Moved in and set up"],
    },
    {
      key: "life-learn-to-drive",
      title: "Learn to drive and pass your test",
      summary: "From first lesson to licence, including the theory and the nerves.",
      category: "certification",
      difficulty: 3,
      weeks: 28,
      tags: ["driving", "licence", "test", "car"],
      skills: ["Vehicle control", "Road awareness and hazard perception", "Manoeuvres", "Theory knowledge", "Test-condition practice"],
      milestones: ["Comfortable with basic control", "Theory test passed", "Driving independently on lessons", "Practical test passed"],
    },
    {
      key: "life-buy-a-car",
      title: "Buy a car without getting stung",
      summary: "Research, inspect and negotiate properly rather than trusting a listing.",
      category: "project",
      difficulty: 2,
      weeks: 8,
      tags: ["car", "buying", "vehicle", "negotiation"],
      skills: ["Needs and budget definition", "Market research", "Inspection and history checks", "Negotiation"],
      milestones: ["Requirements and budget set", "Shortlist built", "Inspections completed", "Purchased at a fair price"],
    },
    {
      key: "life-emergency-preparedness",
      title: "Get properly prepared for emergencies",
      summary: "Documents, supplies and plans so a bad day does not become a crisis.",
      category: "project",
      difficulty: 2,
      weeks: 10,
      tags: ["emergency", "preparedness", "safety", "planning"],
      skills: ["Risk assessment for your area", "Document and data backup", "Supply kit", "Household plan"],
      milestones: ["Risks identified", "Documents backed up", "Kit assembled", "Plan agreed with household"],
    },
    {
      key: "life-first-aid",
      title: "Learn first aid properly",
      summary: "Certified, hands-on training you would actually be able to use under pressure.",
      category: "certification",
      difficulty: 2,
      weeks: 8,
      tags: ["first aid", "cpr", "safety", "certification"],
      skills: ["CPR and defibrillator use", "Bleeding and airway management", "Assessment under pressure", "Certification"],
      milestones: ["Course booked", "CPR competent", "Course completed", "Certification held and refreshed"],
    },
    {
      key: "life-time-management",
      title: "Get control of your time",
      summary: "A trusted system for capture, planning and actually doing the important work.",
      category: "personal_development",
      difficulty: 3,
      weeks: 16,
      tags: ["time management", "productivity", "planning", "focus"],
      skills: ["Capture everything", "Weekly planning", "Prioritisation", "Calendar discipline", "Weekly review"],
      milestones: ["Capture system trusted", "Weekly planning running", "Important work scheduled first", "System survives a busy month"],
    },
    {
      key: "life-beat-procrastination",
      title: "Stop procrastinating",
      summary: "Address the actual causes — ambiguity, aversion and perfectionism — rather than trying harder.",
      category: "habit",
      difficulty: 4,
      weeks: 20,
      tags: ["procrastination", "focus", "discipline", "productivity"],
      skills: ["Task decomposition", "Starting rituals", "Aversion identification", "Environment design", "Self-compassion after slips"],
      milestones: ["Patterns identified honestly", "Starting ritual working", "Long-avoided task completed", "Meaningfully less avoidance"],
    },
    {
      key: "life-deep-work",
      title: "Build a deep work practice",
      summary: "Protect long, undistracted blocks and use them on work that actually matters.",
      category: "habit",
      difficulty: 3,
      weeks: 16,
      tags: ["deep work", "focus", "concentration", "productivity"],
      skills: ["Block scheduling", "Distraction elimination", "Attention endurance", "Shutdown ritual"],
      milestones: ["First 90-minute block completed", "Daily blocks for two weeks", "Three-hour sessions sustainable", "Deep work is the default, not the exception"],
      metric: { name: "Weekly deep work", target: 15, unit: "hours" },
    },
    {
      key: "life-inbox-zero",
      title: "Get your inbox under control",
      summary: "A processing system that keeps email from becoming a second job.",
      category: "habit",
      difficulty: 2,
      weeks: 8,
      tags: ["email", "inbox", "productivity", "admin"],
      skills: ["Backlog processing", "Filtering and rules", "Batch processing", "Fast decisions"],
      milestones: ["Backlog cleared", "Rules and filters set", "Twice-daily processing", "Sustained for a month"],
    },
    {
      key: "life-digital-organisation",
      title: "Organise your digital life",
      summary: "Files, photos, passwords and backups — sorted once, then maintained.",
      category: "project",
      difficulty: 2,
      weeks: 12,
      tags: ["files", "backup", "passwords", "digital", "organisation"],
      skills: ["File structure design", "Photo organisation", "Password manager setup", "Automated backups"],
      milestones: ["Password manager in use", "Files structured", "Photos sorted", "Automated backup verified"],
    },
    {
      key: "life-reduce-waste",
      title: "Reduce your household waste",
      summary: "Practical changes to what you buy and throw away, without moralising about it.",
      category: "habit",
      difficulty: 2,
      weeks: 16,
      tags: ["sustainability", "waste", "recycling", "environment"],
      skills: ["Waste audit", "Purchasing changes", "Repair and reuse", "Correct recycling"],
      milestones: ["Waste audited", "Biggest sources addressed", "Waste noticeably reduced", "New habits sustained"],
    },
    {
      key: "life-energy-efficiency",
      title: "Cut your household energy use",
      summary: "Measure, fix the biggest losses, and reduce both bills and footprint.",
      category: "project",
      difficulty: 2,
      weeks: 14,
      tags: ["energy", "bills", "efficiency", "home"],
      skills: ["Usage measurement", "Insulation and draughts", "Appliance efficiency", "Behaviour changes"],
      milestones: ["Baseline usage measured", "Quick wins done", "Larger improvements made", "Usage measurably lower"],
    },
    {
      key: "life-grow-vegetables",
      title: "Grow your own vegetables",
      summary: "From bare soil or pots to actually harvesting food you planted.",
      category: "project",
      difficulty: 2,
      weeks: 28,
      tags: ["gardening", "vegetables", "growing", "allotment"],
      skills: ["Soil and site preparation", "Sowing and timing", "Watering and feeding", "Pest management", "Harvesting and succession"],
      milestones: ["Beds or pots prepared", "First seedlings established", "First harvest", "Continuous harvest through a season"],
    },
    {
      key: "life-houseplants",
      title: "Keep houseplants alive",
      summary: "Understand light and water well enough to stop killing them.",
      category: "habit",
      difficulty: 1,
      weeks: 12,
      tags: ["houseplants", "plants", "indoor", "gardening"],
      skills: ["Light assessment", "Watering judgement", "Repotting", "Problem diagnosis"],
      milestones: ["Plants matched to light", "Watering routine working", "First repot done", "All plants thriving after three months"],
    },
    {
      key: "life-garden-design",
      title: "Design and plant a garden",
      summary: "Plan a garden that works year-round rather than buying plants at random.",
      category: "project",
      difficulty: 3,
      weeks: 32,
      tags: ["garden", "landscaping", "planting", "design"],
      skills: ["Site and soil assessment", "Design and planting plan", "Planting technique", "Seasonal maintenance"],
      milestones: ["Site assessed and plan drawn", "Structure and beds prepared", "Main planting done", "Garden established through a full season"],
    },
    {
      key: "life-minimalism",
      title: "Live with much less",
      summary: "A deliberate reduction in possessions and commitments, kept up over time.",
      category: "personal_development",
      difficulty: 3,
      weeks: 24,
      tags: ["minimalism", "simplify", "possessions", "intentional"],
      skills: ["Value clarification", "Systematic reduction", "Purchase resistance", "Commitment pruning"],
      milestones: ["Values clarified", "Possessions substantially reduced", "Buying habits changed", "Sustained for six months"],
    },
    {
      key: "life-plan-wedding",
      title: "Plan a wedding without losing your mind",
      summary: "Budget, sequence and delegate so the planning does not eat the year.",
      category: "project",
      difficulty: 3,
      weeks: 40,
      tags: ["wedding", "planning", "event", "budget"],
      skills: ["Budget setting", "Vendor selection", "Timeline management", "Guest logistics", "Delegation"],
      milestones: ["Budget and guest list agreed", "Venue and key vendors booked", "Details finalised", "Wedding day delivered"],
    },
    {
      key: "life-estate-planning",
      title: "Sort out your will and affairs",
      summary: "The paperwork that spares the people you care about a great deal of difficulty.",
      category: "project",
      difficulty: 2,
      weeks: 12,
      tags: ["will", "estate", "legal", "planning"],
      skills: ["Asset inventory", "Will preparation", "Beneficiary and nomination updates", "Document accessibility"],
      milestones: ["Assets inventoried", "Will drafted", "Will executed properly", "Documents stored and findable"],
    },
    {
      key: "life-care-for-parent",
      title: "Support an ageing parent",
      summary: "Practical, financial and emotional planning — including looking after yourself.",
      category: "personal_development",
      difficulty: 4,
      weeks: 52,
      tags: ["caring", "parents", "ageing", "family"],
      skills: ["Needs assessment", "Navigating services", "Family coordination", "Financial and legal admin", "Carer self-care"],
      milestones: ["Needs honestly assessed", "Support services engaged", "Family roles agreed", "Sustainable arrangement in place"],
    },
    {
      key: "life-new-baby",
      title: "Prepare for a new baby",
      summary: "The practical, financial and relationship preparation, not just the nursery.",
      category: "project",
      difficulty: 3,
      weeks: 36,
      tags: ["baby", "parenting", "pregnancy", "preparation"],
      skills: ["Practical preparation", "Financial planning", "Knowledge and skills", "Support network", "Relationship planning"],
      milestones: ["Essentials and finances planned", "Practical skills learned", "Support network arranged", "Ready for the birth"],
    },
    {
      key: "life-adopt-a-pet",
      title: "Get ready for a pet",
      summary: "Honest preparation for the time, cost and commitment before bringing an animal home.",
      category: "project",
      difficulty: 2,
      weeks: 12,
      tags: ["pet", "dog", "cat", "adoption"],
      skills: ["Honest suitability assessment", "Cost planning", "Home preparation", "Training knowledge"],
      milestones: ["Suitability and costs assessed", "Home prepared", "Pet adopted", "Settled in with a routine"],
    },
    {
      key: "life-train-a-dog",
      title: "Train your dog properly",
      summary: "Reliable recall and manners through consistent, reward-based training.",
      category: "habit",
      difficulty: 3,
      weeks: 24,
      tags: ["dog", "training", "obedience", "pet"],
      skills: ["Reward-based technique", "Consistency across the household", "Recall training", "Socialisation", "Problem behaviour management"],
      milestones: ["Basic cues reliable at home", "Reliable in the garden", "Reliable in public", "Recall reliable off-lead"],
    },
  ],
};
