import type { TemplateDomain, TemplateSpec } from "../types";

/**
 * Money templates are deliberately generic about jurisdiction — tax rules,
 * account types and retirement schemes differ by country, so plans focus on
 * the behaviour (save, invest, reduce debt) rather than naming products.
 */

const SAVINGS_TARGETS = [
  { slug: "1k", amount: 1000, label: "£1,000 / $1,000", weeks: 16, difficulty: 2 },
  { slug: "5k", amount: 5000, label: "5,000", weeks: 40, difficulty: 3 },
  { slug: "10k", amount: 10000, label: "10,000", weeks: 60, difficulty: 3 },
  { slug: "25k", amount: 25000, label: "25,000", weeks: 104, difficulty: 4 },
  { slug: "50k", amount: 50000, label: "50,000", weeks: 156, difficulty: 4 },
  { slug: "100k", amount: 100000, label: "100,000", weeks: 260, difficulty: 5 },
];

const savingsTemplates: TemplateSpec[] = SAVINGS_TARGETS.map((t) => ({
  key: `money-save-${t.slug}`,
  title: `Save ${t.label}`,
  summary: `Build a savings balance of ${t.label} through a rate you can actually sustain, not heroic short-term restriction.`,
  category: "finance",
  difficulty: t.difficulty,
  weeks: t.weeks,
  tags: ["saving", "savings", "money", "goal", t.slug],
  skills: ["Spending awareness", "Automated saving", "Cutting recurring costs", "Income growth", "Progress tracking"],
  milestones: ["Baseline and monthly rate set", "25% saved", "Half saved", "Target reached"],
  metric: { name: "Saved", target: t.amount },
}));

const extras: TemplateSpec[] = [
  {
    key: "money-budget",
    title: "Build a budget you'll actually stick to",
    summary: "Understand where your money goes, then design a plan that survives real life.",
    category: "finance",
    difficulty: 2,
    weeks: 12,
    tags: ["budget", "spending", "money", "planning"],
    skills: ["Expense tracking", "Category design", "Realistic limits", "Weekly review"],
    milestones: ["One month tracked honestly", "Budget drafted", "First month within budget", "Three months sustained"],
  },
  {
    key: "money-emergency-fund",
    title: "Build a three-month emergency fund",
    summary: "The buffer that turns a financial emergency into an inconvenience.",
    category: "finance",
    difficulty: 3,
    weeks: 52,
    tags: ["emergency fund", "savings", "security", "buffer"],
    skills: ["Essential expense calculation", "Automated transfers", "Keeping it untouched", "Rate optimisation"],
    milestones: ["Target amount calculated", "One month's expenses saved", "Two months saved", "Three months saved"],
  },
  {
    key: "money-clear-debt",
    title: "Clear your consumer debt",
    summary: "A structured payoff plan that keeps momentum instead of collapsing after month two.",
    category: "finance",
    difficulty: 4,
    weeks: 78,
    tags: ["debt", "credit card", "payoff", "loans"],
    skills: ["Full debt inventory", "Payoff strategy", "Interest reduction", "Spending control", "Income increase"],
    milestones: ["All debts listed with rates", "Highest-rate debt cleared", "Half of total cleared", "Debt free"],
  },
  {
    key: "money-start-investing",
    title: "Start investing sensibly",
    summary: "Understand the basics well enough to invest without gambling or freezing.",
    category: "finance",
    difficulty: 3,
    weeks: 24,
    tags: ["investing", "index funds", "portfolio", "compound"],
    skills: ["Risk and time horizon", "Diversification", "Fees and their effect", "Automated contributions", "Behaviour during downturns"],
    milestones: ["Fundamentals understood", "Account opened", "First contribution made", "Automated and running for six months"],
  },
  {
    key: "money-retirement",
    title: "Get your retirement savings on track",
    summary: "Work out what you actually need and close the gap while time is still on your side.",
    category: "finance",
    difficulty: 3,
    weeks: 32,
    tags: ["retirement", "pension", "long term", "compound"],
    skills: ["Projection and target setting", "Contribution optimisation", "Fee reduction", "Allocation review"],
    milestones: ["Current position calculated", "Target and gap identified", "Contributions increased", "On track by projection"],
  },
  {
    key: "money-house-deposit",
    title: "Save a house deposit",
    summary: "A long, structured savings campaign with the timeline made explicit.",
    category: "finance",
    difficulty: 4,
    weeks: 156,
    tags: ["house", "deposit", "mortgage", "property", "saving"],
    skills: ["Target and timeline calculation", "Aggressive saving rate", "Income growth", "Cost reduction", "Mortgage readiness"],
    milestones: ["Target and timeline set", "25% of deposit saved", "Half saved", "Deposit complete and mortgage-ready"],
  },
  {
    key: "money-side-income",
    title: "Build a second income stream",
    summary: "Add income rather than only cutting costs — usually the faster lever.",
    category: "business",
    difficulty: 3,
    weeks: 40,
    tags: ["side hustle", "income", "freelance", "extra money"],
    skills: ["Opportunity selection", "Offer and pricing", "First customers", "Time management", "Reinvestment"],
    milestones: ["Idea chosen and validated", "First payment received", "Consistent monthly income", "Meaningful share of main income"],
  },
  {
    key: "money-financial-literacy",
    title: "Understand personal finance properly",
    summary: "Cover the whole picture — tax, insurance, credit, investing — instead of picking it up piecemeal.",
    category: "education",
    difficulty: 3,
    weeks: 24,
    tags: ["financial literacy", "money", "education", "personal finance"],
    skills: ["Income and tax basics", "Credit and borrowing", "Insurance and protection", "Investing fundamentals", "Estate and planning basics"],
    milestones: ["Income and tax understood", "Credit position understood", "Protection reviewed", "Full personal finance plan written"],
  },
  {
    key: "money-negotiate-bills",
    title: "Cut your recurring costs",
    summary: "One focused sweep through subscriptions, utilities and insurance usually beats months of small savings.",
    category: "finance",
    difficulty: 1,
    weeks: 6,
    tags: ["bills", "subscriptions", "saving", "costs"],
    skills: ["Recurring cost audit", "Comparison shopping", "Negotiation scripts", "Cancellation follow-through"],
    milestones: ["All recurring costs listed", "Unused subscriptions cancelled", "Three bills renegotiated", "Monthly outgoings meaningfully lower"],
  },
  {
    key: "money-stop-impulse-spending",
    title: "Stop impulse spending",
    summary: "Identify your triggers and build friction where it matters.",
    category: "habit",
    difficulty: 3,
    weeks: 16,
    tags: ["impulse", "spending", "habit", "self-control"],
    skills: ["Trigger identification", "Friction design", "Waiting rules", "Replacement behaviours"],
    milestones: ["Triggers identified", "Friction in place", "One month without an impulse purchase", "Three months sustained"],
  },
  {
    key: "money-track-net-worth",
    title: "Track your net worth properly",
    summary: "One number, updated monthly, that tells you whether things are actually improving.",
    category: "habit",
    difficulty: 1,
    weeks: 12,
    tags: ["net worth", "tracking", "assets", "money"],
    skills: ["Asset and liability inventory", "Monthly update habit", "Trend interpretation"],
    milestones: ["First full calculation done", "Three months tracked", "Six months tracked", "Trend clear and improving"],
  },
  {
    key: "money-tax-return",
    title: "Do your own tax return confidently",
    summary: "Understand your own tax position instead of guessing or overpaying.",
    category: "finance",
    difficulty: 2,
    weeks: 10,
    tags: ["tax", "return", "deductions", "compliance"],
    skills: ["Record keeping", "Allowable deductions", "Filing process", "Deadline management"],
    milestones: ["Records organised", "Deductions identified", "Return drafted", "Filed on time"],
  },
  {
    key: "money-teach-kids",
    title: "Teach your kids about money",
    summary: "Age-appropriate lessons that build genuine financial instincts early.",
    category: "personal_development",
    difficulty: 2,
    weeks: 24,
    tags: ["kids", "parenting", "money", "education"],
    skills: ["Age-appropriate framing", "Allowance and earning systems", "Saving and delayed gratification", "Talking about money openly"],
    milestones: ["System agreed with them", "Saving toward a chosen goal", "First goal reached by them", "Habit established"],
  },
  {
    key: "money-financial-independence",
    title: "Reach financial independence",
    summary: "The long game — invested assets large enough to cover your living costs.",
    category: "finance",
    difficulty: 5,
    weeks: 400,
    tags: ["fire", "financial independence", "early retirement", "investing"],
    skills: ["Savings rate maximisation", "Investment strategy", "Lifestyle design", "Income growth", "Long-horizon discipline"],
    milestones: ["Target number calculated", "25% of target invested", "Half of target invested", "Target reached"],
  },
];

export const money: TemplateDomain = {
  key: "money",
  label: "Money",
  blurb: "Saving, debt, investing, income and understanding your own finances.",
  templates: [...savingsTemplates, ...extras],
};
