import type { TemplateDomain } from "../types";

export const people: TemplateDomain = {
  key: "people",
  label: "Relationships & people",
  blurb: "Friendships, family, partners, communication and community.",
  templates: [
    {
      key: "people-make-friends",
      title: "Make new friends as an adult",
      summary: "Friendship after school takes deliberate repetition and initiative. Treat it as a skill.",
      category: "personal_development",
      difficulty: 3,
      weeks: 32,
      tags: ["friends", "friendship", "social", "connection"],
      skills: ["Repeated exposure through activities", "Initiating plans", "Following up", "Moving past small talk"],
      milestones: ["A recurring activity joined", "Five people you see regularly", "First one-to-one plan made", "Two genuine friendships"],
    },
    {
      key: "people-deepen-friendships",
      title: "Deepen the friendships you already have",
      summary: "Most people have enough acquaintances and not enough close friends.",
      category: "personal_development",
      difficulty: 2,
      weeks: 24,
      tags: ["friendship", "closeness", "connection", "depth"],
      skills: ["Consistent contact", "Real conversation", "Showing up when it matters", "Reciprocity"],
      milestones: ["Regular contact rhythm", "A genuinely honest conversation", "Supported someone through something hard", "Noticeably closer"],
    },
    {
      key: "people-reconnect",
      title: "Reconnect with people you've lost touch with",
      summary: "The awkwardness of reaching out is almost always smaller than you think.",
      category: "personal_development",
      difficulty: 2,
      weeks: 16,
      tags: ["reconnect", "friendship", "outreach", "relationships"],
      skills: ["Getting over the initial awkwardness", "Honest openers", "Rebuilding rhythm"],
      milestones: ["List made", "First message sent", "Five reconnections", "Two relationships genuinely revived"],
    },
    {
      key: "people-better-listener",
      title: "Become a genuinely good listener",
      summary: "Most people listen to reply. This is the skill that changes every relationship you have.",
      category: "personal_development",
      difficulty: 3,
      weeks: 20,
      tags: ["listening", "communication", "empathy", "relationships"],
      skills: ["Not interrupting", "Asking rather than assuming", "Reflecting back", "Sitting with discomfort"],
      milestones: ["Noticing when you interrupt", "Asking more than you tell", "People opening up more", "Habitual, not effortful"],
    },
    {
      key: "people-difficult-conversations",
      title: "Get better at difficult conversations",
      summary: "Raise problems early and directly instead of avoiding them until they detonate.",
      category: "personal_development",
      difficulty: 4,
      weeks: 24,
      tags: ["conflict", "communication", "confrontation", "honesty"],
      skills: ["Preparing without scripting", "Separating behaviour from character", "Staying regulated", "Repair afterwards"],
      milestones: ["One avoided conversation identified", "First conversation held", "Handled one that went badly, well", "Raising things early by default"],
    },
    {
      key: "people-set-boundaries",
      title: "Learn to set boundaries",
      summary: "Say no clearly and without a paragraph of justification.",
      category: "personal_development",
      difficulty: 4,
      weeks: 24,
      tags: ["boundaries", "no", "assertiveness", "self-respect"],
      skills: ["Noticing resentment as a signal", "Clear, brief refusals", "Tolerating other people's disappointment", "Holding the boundary"],
      milestones: ["Patterns identified", "First clear no", "Held a boundary under pressure", "Boundaries are normal, not dramatic"],
    },
    {
      key: "people-small-talk",
      title: "Get comfortable with small talk",
      summary: "The gateway skill to every other social interaction, and entirely learnable.",
      category: "personal_development",
      difficulty: 2,
      weeks: 16,
      tags: ["small talk", "conversation", "social", "confidence"],
      skills: ["Openers", "Asking follow-up questions", "Finding shared ground", "Exiting gracefully"],
      milestones: ["Ten conversations with strangers", "Comfortable at an event alone", "Genuinely enjoying it sometimes", "No longer avoiding situations"],
    },
    {
      key: "people-social-anxiety",
      title: "Work through social anxiety",
      summary: "Graded exposure and thought work, with professional support where it is warranted.",
      category: "personal_development",
      difficulty: 4,
      weeks: 32,
      tags: ["social anxiety", "anxiety", "exposure", "confidence"],
      skills: ["Situation hierarchy", "Cognitive reframing", "Graded exposure", "Dropping safety behaviours", "Support"],
      milestones: ["Hierarchy written", "Easiest situations faced repeatedly", "A genuinely hard situation faced", "Meaningfully less avoidance"],
    },
    {
      key: "people-date",
      title: "Start dating with intention",
      summary: "Clarity about what you want, and the practical habits to actually meet people.",
      category: "personal_development",
      difficulty: 3,
      weeks: 28,
      tags: ["dating", "relationships", "romance", "meeting people"],
      skills: ["Clarity about what you want", "Meeting people regularly", "Conversation and connection", "Handling rejection", "Honest early communication"],
      milestones: ["Clear on what you're looking for", "Meeting people regularly", "Several dates had", "Dating someone you actually like"],
    },
    {
      key: "people-strengthen-relationship",
      title: "Strengthen your relationship",
      summary: "Deliberate maintenance rather than assuming it looks after itself.",
      category: "personal_development",
      difficulty: 3,
      weeks: 32,
      tags: ["relationship", "partner", "marriage", "couple"],
      skills: ["Protected time together", "Repair after conflict", "Appreciation as a habit", "Honest check-ins", "Shared plans"],
      milestones: ["Regular time protected", "Conflicts repairing faster", "Honest check-in rhythm", "Noticeably better connection"],
    },
    {
      key: "people-couples-therapy",
      title: "Work on your relationship with professional help",
      summary: "Get support early rather than as a last resort, and do the work between sessions.",
      category: "personal_development",
      difficulty: 4,
      weeks: 36,
      tags: ["couples therapy", "counselling", "relationship", "support"],
      skills: ["Agreeing to go", "Finding the right therapist", "Between-session practice", "Staying with it through discomfort"],
      milestones: ["Both agreed", "First session attended", "Six sessions in", "Patterns genuinely shifting"],
    },
    {
      key: "people-end-relationship",
      title: "End a relationship well",
      summary: "Leaving with as much clarity and decency as the situation allows.",
      category: "personal_development",
      difficulty: 4,
      weeks: 24,
      tags: ["breakup", "separation", "ending", "relationship"],
      skills: ["Getting clear on the decision", "Having the conversation", "Practical separation", "Grieving properly", "Rebuilding"],
      milestones: ["Decision made and understood", "Conversation had", "Practicalities separated", "Steady again"],
    },
    {
      key: "people-better-parent",
      title: "Become a more present parent",
      summary: "Attention and consistency, not more activities or more guilt.",
      category: "personal_development",
      difficulty: 3,
      weeks: 32,
      tags: ["parenting", "children", "family", "presence"],
      skills: ["Undistracted attention", "Consistent routines", "Emotion coaching", "Repair after losing your temper"],
      milestones: ["Daily undistracted time protected", "Routines steady", "Handling meltdowns better", "Noticeably better connection"],
    },
    {
      key: "people-teenager-relationship",
      title: "Stay connected to your teenager",
      summary: "Keep the relationship open through the years when they naturally pull away.",
      category: "personal_development",
      difficulty: 4,
      weeks: 40,
      tags: ["teenager", "parenting", "adolescent", "family"],
      skills: ["Listening without immediately fixing", "Picking battles", "Being available on their timing", "Respecting growing autonomy"],
      milestones: ["Regular low-pressure time", "They initiated a conversation", "A hard topic handled well", "Relationship genuinely open"],
    },
    {
      key: "people-family-relationship",
      title: "Repair a difficult family relationship",
      summary: "Slow, realistic work with honest expectations about what may or may not change.",
      category: "personal_development",
      difficulty: 4,
      weeks: 44,
      tags: ["family", "repair", "estrangement", "reconciliation"],
      skills: ["Realistic expectations", "Initiating contact", "Boundaries alongside repair", "Accepting limits"],
      milestones: ["Own contribution understood", "Contact re-established", "A real conversation had", "A workable relationship, whatever its shape"],
    },
    {
      key: "people-forgive",
      title: "Let go of a long-held resentment",
      summary: "Forgiveness as something you do for your own sake, not as approval of what happened.",
      category: "personal_development",
      difficulty: 4,
      weeks: 32,
      tags: ["forgiveness", "resentment", "letting go", "healing"],
      skills: ["Naming the hurt precisely", "Separating forgiveness from reconciliation", "Processing with support", "Releasing rumination"],
      milestones: ["Hurt named honestly", "Worked through with support", "Rumination reduced", "Genuinely lighter about it"],
    },
    {
      key: "people-networking-genuine",
      title: "Build professional relationships that aren't transactional",
      summary: "Be useful to people consistently and the network builds itself.",
      category: "career",
      difficulty: 2,
      weeks: 32,
      tags: ["networking", "professional", "relationships", "career"],
      skills: ["Being useful first", "Staying in touch without an ask", "Making introductions", "Consistency"],
      milestones: ["Ten people contacted with no ask", "Made three useful introductions", "Regular contact rhythm", "Genuine professional community"],
    },
    {
      key: "people-mentor",
      title: "Find a mentor",
      summary: "Approach people properly and make it worth their time.",
      category: "career",
      difficulty: 3,
      weeks: 24,
      tags: ["mentor", "guidance", "career", "learning"],
      skills: ["Identifying the right people", "Approaching well", "Preparing for sessions", "Acting on advice"],
      milestones: ["Shortlist identified", "First conversation had", "Regular sessions running", "Visible progress from the relationship"],
    },
    {
      key: "people-be-a-mentor",
      title: "Mentor someone else",
      summary: "Pass on what you know, and understand it better in the process.",
      category: "personal_development",
      difficulty: 3,
      weeks: 28,
      tags: ["mentoring", "teaching", "giving back", "leadership"],
      skills: ["Listening before advising", "Asking useful questions", "Honest feedback", "Consistency"],
      milestones: ["Mentee found", "Regular sessions running", "They hit a real milestone", "Genuinely useful to them"],
    },
    {
      key: "people-volunteer",
      title: "Volunteer regularly",
      summary: "Find something that actually needs doing and show up for it consistently.",
      category: "personal_development",
      difficulty: 2,
      weeks: 28,
      tags: ["volunteering", "community", "giving back", "service"],
      skills: ["Finding a genuine need", "Realistic commitment", "Consistency", "Working within an organisation"],
      milestones: ["Organisation chosen", "First session done", "Three months regular", "Trusted with real responsibility"],
    },
    {
      key: "people-community-project",
      title: "Start a community project",
      summary: "Organise something local that would not exist unless someone made it happen.",
      category: "project",
      difficulty: 4,
      weeks: 44,
      tags: ["community", "local", "organising", "project"],
      skills: ["Identifying a real need", "Recruiting others", "Funding and permissions", "Delivery", "Sustainability"],
      milestones: ["Need identified and tested", "Core group recruited", "First activity delivered", "Running without you driving everything"],
    },
    {
      key: "people-activism",
      title: "Get involved in a cause you care about",
      summary: "Move from having opinions to doing something consistent and useful.",
      category: "personal_development",
      difficulty: 3,
      weeks: 32,
      tags: ["activism", "cause", "advocacy", "community"],
      skills: ["Understanding the issue properly", "Finding effective organisations", "Consistent contribution", "Avoiding burnout"],
      milestones: ["Issue understood in depth", "Group joined", "Contributing regularly", "Meaningful contribution made"],
    },
    {
      key: "people-host-gatherings",
      title: "Become someone who brings people together",
      summary: "Regular gatherings are how adult friend groups actually survive.",
      category: "personal_development",
      difficulty: 2,
      weeks: 24,
      tags: ["hosting", "gathering", "community", "friends"],
      skills: ["Lowering the bar to host", "Inviting well", "Facilitating a group", "Making it recurring"],
      milestones: ["First gathering hosted", "Three hosted", "It became recurring", "People ask when the next one is"],
    },
    {
      key: "people-say-thank-you",
      title: "Tell people what they mean to you",
      summary: "Specific, direct appreciation — the thing most people intend to do and never quite do.",
      category: "habit",
      difficulty: 1,
      weeks: 12,
      tags: ["gratitude", "appreciation", "relationships", "kindness"],
      skills: ["Specificity over generality", "Overcoming awkwardness", "Doing it promptly"],
      milestones: ["First message sent", "Five people told", "Ten people told", "It became normal for you"],
    },
  ],
};
