import type { TemplateDomain, TemplateSpec } from "../types";

interface Lang {
  slug: string;
  name: string;
  /** What people actually build with it — keeps the plan concrete. */
  focus: string;
}

const LANGUAGES: Lang[] = [
  { slug: "python", name: "Python", focus: "scripts, data work and backends" },
  { slug: "javascript", name: "JavaScript", focus: "interactive web apps" },
  { slug: "typescript", name: "TypeScript", focus: "type-safe web applications" },
  { slug: "java", name: "Java", focus: "backend services and Android" },
  { slug: "csharp", name: "C#", focus: ".NET apps and Unity games" },
  { slug: "cpp", name: "C++", focus: "performance-critical systems" },
  { slug: "c", name: "C", focus: "systems and embedded programming" },
  { slug: "rust", name: "Rust", focus: "safe systems programming" },
  { slug: "go", name: "Go", focus: "network services and tooling" },
  { slug: "swift", name: "Swift", focus: "iOS and macOS apps" },
  { slug: "kotlin", name: "Kotlin", focus: "modern Android apps" },
  { slug: "ruby", name: "Ruby", focus: "web apps with Rails" },
  { slug: "php", name: "PHP", focus: "server-rendered web apps" },
  { slug: "sql", name: "SQL", focus: "querying and shaping data" },
  { slug: "r", name: "R", focus: "statistics and data visualisation" },
  { slug: "matlab", name: "MATLAB", focus: "engineering and numerical work" },
  { slug: "scala", name: "Scala", focus: "data pipelines and JVM services" },
  { slug: "elixir", name: "Elixir", focus: "highly concurrent services" },
  { slug: "haskell", name: "Haskell", focus: "purely functional programming" },
  { slug: "lua", name: "Lua", focus: "game scripting and embedded logic" },
  { slug: "dart", name: "Dart", focus: "cross-platform Flutter apps" },
  { slug: "bash", name: "Bash", focus: "automation and shell tooling" },
];

function learnLang(l: Lang): TemplateSpec {
  return {
    key: `tech-learn-${l.slug}`,
    title: `Learn ${l.name}`,
    summary: `Get genuinely productive in ${l.name} — enough to build ${l.focus} without following a tutorial line by line.`,
    category: "programming",
    difficulty: 3,
    weeks: 20,
    tags: [l.slug, l.name.toLowerCase(), "programming", "coding", "software"],
    skills: ["Syntax and fundamentals", "Data structures", "Idiomatic patterns", "Tooling and debugging", "Project building"],
    milestones: [
      "Environment set up, first programs running",
      "Comfortable with core syntax and data structures",
      "Built a small program unaided",
      `Shipped a non-trivial ${l.name} project`,
    ],
  };
}

const generated = LANGUAGES.map(learnLang);

const extras: TemplateSpec[] = [
  {
    key: "tech-first-dev-job",
    title: "Land your first software developer job",
    summary: "Build the skills, portfolio and interview performance to get hired as a junior developer.",
    category: "career",
    difficulty: 4,
    weeks: 52,
    tags: ["career", "job", "junior developer", "interview", "portfolio"],
    skills: ["Core language proficiency", "Data structures and algorithms", "Portfolio projects", "System design basics", "Interview technique", "Applications and networking"],
    milestones: ["Core language solid", "Two portfolio projects shipped", "100 practice problems solved", "Passing mock interviews", "Offer accepted"],
  },
  {
    key: "tech-leetcode-interview",
    title: "Pass a technical coding interview",
    summary: "Systematic algorithm practice until interview problems become recognisable patterns.",
    category: "programming",
    difficulty: 4,
    weeks: 20,
    tags: ["leetcode", "algorithms", "interview", "data structures"],
    skills: ["Arrays and strings", "Trees and graphs", "Dynamic programming", "Complexity analysis", "Communicating while coding"],
    milestones: ["50 easy problems", "75 medium problems", "Timed mock interview passed", "Consistent on unseen mediums"],
    metric: { name: "Problems solved", target: 150, unit: "problems" },
  },
  {
    key: "tech-system-design",
    title: "Get good at system design",
    summary: "Learn to design and defend scalable architectures in interviews and at work.",
    category: "programming",
    difficulty: 4,
    weeks: 24,
    tags: ["system design", "architecture", "scalability", "interview"],
    skills: ["Storage and caching", "Scaling patterns", "Consistency trade-offs", "API and schema design", "Whiteboard communication"],
    milestones: ["Core building blocks understood", "Design a URL shortener end to end", "Design a feed system", "Pass a mock design interview"],
  },
  {
    key: "tech-build-saas",
    title: "Build and launch a SaaS product",
    summary: "Take a software idea from nothing to paying users.",
    category: "business",
    difficulty: 5,
    weeks: 52,
    tags: ["saas", "startup", "product", "launch", "indie hacking"],
    skills: ["Customer discovery", "Product scoping", "Full-stack build", "Payments and auth", "Launch and marketing", "Support and iteration"],
    milestones: ["Problem validated with 10 conversations", "MVP built", "First live user", "First paying customer", "Ten paying customers"],
  },
  {
    key: "tech-ship-mobile-app",
    title: "Ship a mobile app to the app store",
    summary: "Build, polish and actually publish an app through review to real users.",
    category: "project",
    difficulty: 4,
    weeks: 32,
    tags: ["mobile", "ios", "android", "app store", "launch"],
    skills: ["Mobile framework", "UI and navigation", "Local storage and state", "Store submission", "Post-launch iteration"],
    milestones: ["App runs on a real device", "Core feature complete", "Beta testers onboarded", "Published and live"],
  },
  {
    key: "tech-personal-website",
    title: "Build your own personal website",
    summary: "A portfolio site you own, deployed on your own domain.",
    category: "project",
    difficulty: 2,
    weeks: 8,
    tags: ["portfolio", "website", "html", "css", "deploy"],
    skills: ["HTML and CSS", "Layout and responsiveness", "Content and copy", "Deployment"],
    milestones: ["Page renders locally", "Responsive on mobile", "Deployed to a live URL", "Custom domain connected"],
  },
  {
    key: "tech-contribute-open-source",
    title: "Get a pull request merged into open source",
    summary: "Navigate a real codebase and land a contribution that maintainers accept.",
    category: "programming",
    difficulty: 3,
    weeks: 16,
    tags: ["open source", "github", "contribution", "collaboration"],
    skills: ["Git and PR workflow", "Reading unfamiliar code", "Project conventions", "Code review communication"],
    milestones: ["Project chosen and built locally", "First issue understood", "PR opened", "PR merged"],
  },
  {
    key: "tech-learn-git",
    title: "Actually understand Git",
    summary: "Move past memorised commands to a real mental model of branches, merges and history.",
    category: "programming",
    difficulty: 2,
    weeks: 6,
    tags: ["git", "version control", "github", "branching"],
    skills: ["Commits and history", "Branching and merging", "Rebasing", "Undoing mistakes"],
    milestones: ["Commit and branch confidently", "Resolve a merge conflict", "Rebase a feature branch", "Recover from a bad mistake"],
  },
  {
    key: "tech-devops-pipeline",
    title: "Set up CI/CD for a real project",
    summary: "Automate testing and deployment so shipping stops being manual and scary.",
    category: "programming",
    difficulty: 3,
    weeks: 12,
    tags: ["devops", "ci", "cd", "automation", "deployment"],
    skills: ["Pipeline configuration", "Automated testing", "Containerisation", "Deployment automation", "Monitoring"],
    milestones: ["Tests run on every push", "Build artefacts produced", "Automated deploy to staging", "Automated deploy to production"],
  },
  {
    key: "tech-learn-docker",
    title: "Learn Docker and containers",
    summary: "Containerise applications and understand what is actually happening underneath.",
    category: "programming",
    difficulty: 3,
    weeks: 10,
    tags: ["docker", "containers", "devops", "kubernetes"],
    skills: ["Images and layers", "Dockerfiles", "Networking and volumes", "Compose and orchestration"],
    milestones: ["Run an existing image", "Write a working Dockerfile", "Multi-service compose stack", "Deploy a containerised app"],
  },
  {
    key: "tech-machine-learning",
    title: "Learn machine learning fundamentals",
    summary: "Understand the maths and mechanics well enough to build and evaluate real models.",
    category: "education",
    difficulty: 4,
    weeks: 40,
    tags: ["machine learning", "ai", "data science", "python", "models"],
    skills: ["Linear algebra and statistics", "Supervised learning", "Model evaluation", "Neural networks", "Practical projects"],
    milestones: ["Maths foundations in place", "First model trained and evaluated", "Neural network built from scratch", "End-to-end project completed"],
  },
  {
    key: "tech-data-analyst",
    title: "Become a data analyst",
    summary: "The full skill set — SQL, spreadsheets, visualisation and communicating findings.",
    category: "career",
    difficulty: 4,
    weeks: 40,
    tags: ["data", "analytics", "sql", "dashboards", "career"],
    skills: ["SQL", "Spreadsheet modelling", "Statistics", "Visualisation", "Stakeholder communication", "Portfolio projects"],
    milestones: ["SQL comfortable on real data", "First dashboard built", "Portfolio of three analyses", "Job-ready and applying"],
  },
  {
    key: "tech-cybersecurity-basics",
    title: "Learn practical cybersecurity",
    summary: "Understand common attacks and defences well enough to secure real systems.",
    category: "education",
    difficulty: 4,
    weeks: 32,
    tags: ["security", "cybersecurity", "hacking", "defence"],
    skills: ["Networking fundamentals", "Common vulnerability classes", "Secure configuration", "Monitoring and response", "Hands-on labs"],
    milestones: ["Networking fundamentals solid", "Completed introductory labs", "Secured a test environment", "Capture-the-flag challenge solved"],
  },
  {
    key: "tech-cloud-certification",
    title: "Pass a cloud certification",
    summary: "Structured preparation for an AWS, Azure or GCP associate-level certification.",
    category: "certification",
    difficulty: 3,
    weeks: 16,
    tags: ["aws", "azure", "gcp", "cloud", "certification"],
    skills: ["Core services", "Hands-on labs", "Exam blueprint coverage", "Practice exams", "Weak-domain review"],
    milestones: ["Blueprint mapped", "All domains covered once", "Consistent practice-exam passes", "Certification passed"],
  },
  {
    key: "tech-touch-typing",
    title: "Learn to touch type at 80 WPM",
    summary: "Stop looking at the keyboard and type accurately at speed.",
    category: "habit",
    difficulty: 2,
    weeks: 12,
    tags: ["typing", "wpm", "productivity", "keyboard"],
    skills: ["Correct finger placement", "Accuracy before speed", "Daily drills"],
    milestones: ["Type without looking", "40 WPM at 95% accuracy", "60 WPM", "80 WPM"],
    metric: { name: "Typing speed", target: 80, unit: "wpm" },
  },
  {
    key: "tech-build-game",
    title: "Build and release a small game",
    summary: "Scope something finishable, build it, and actually put it in front of players.",
    category: "project",
    difficulty: 4,
    weeks: 28,
    tags: ["game dev", "unity", "godot", "indie", "release"],
    skills: ["Game engine basics", "Core loop design", "Art and audio pipeline", "Playtesting", "Release and distribution"],
    milestones: ["Playable prototype", "Core loop fun in playtests", "Content complete", "Released publicly"],
  },
  {
    key: "tech-home-server",
    title: "Run your own home server",
    summary: "Self-host your services with sensible backups and security.",
    category: "project",
    difficulty: 3,
    weeks: 12,
    tags: ["homelab", "self-hosting", "server", "linux", "nas"],
    skills: ["Linux administration", "Networking and DNS", "Service deployment", "Backups", "Security hardening"],
    milestones: ["Server running and reachable", "First service self-hosted", "Automated backups working", "Secured and stable for a month"],
  },
  {
    key: "tech-learn-linux",
    title: "Get comfortable on the Linux command line",
    summary: "Navigate, script and administer a Linux system without reaching for a GUI.",
    category: "programming",
    difficulty: 3,
    weeks: 14,
    tags: ["linux", "terminal", "bash", "sysadmin", "cli"],
    skills: ["Filesystem and navigation", "Permissions and processes", "Shell scripting", "Package and service management"],
    milestones: ["Navigate confidently", "Write a useful script", "Manage services and users", "Administer a live box"],
  },
];

export const tech: TemplateDomain = {
  key: "tech",
  label: "Tech & programming",
  blurb: "Software, data, infrastructure and getting hired to build things.",
  templates: [...generated, ...extras],
};
