import type { TemplateDomain, TemplateSpec } from "../types";

interface Destination {
  slug: string;
  name: string;
  /** What planning this trip specifically demands. */
  planning: string;
  /** Typical saving and planning runway, in weeks. */
  weeks: number;
  difficulty: number;
}

const DESTINATIONS: Destination[] = [
  { slug: "japan", name: "Japan", planning: "Rail passes and seasonal timing", weeks: 32, difficulty: 3 },
  { slug: "italy", name: "Italy", planning: "Regional routing and shoulder-season timing", weeks: 24, difficulty: 2 },
  { slug: "france", name: "France", planning: "Regional routing and rail booking", weeks: 24, difficulty: 2 },
  { slug: "spain", name: "Spain", planning: "Regional routing and seasonal heat", weeks: 24, difficulty: 2 },
  { slug: "greece", name: "Greece", planning: "Island ferry logistics", weeks: 24, difficulty: 2 },
  { slug: "portugal", name: "Portugal", planning: "Regional routing and transport", weeks: 20, difficulty: 2 },
  { slug: "iceland", name: "Iceland", planning: "Weather windows and vehicle hire", weeks: 32, difficulty: 3 },
  { slug: "norway", name: "Norway", planning: "Cost management and daylight seasons", weeks: 32, difficulty: 3 },
  { slug: "scotland", name: "Scotland", planning: "Weather and remote-area logistics", weeks: 20, difficulty: 2 },
  { slug: "ireland", name: "Ireland", planning: "Driving routes and weather", weeks: 20, difficulty: 2 },
  { slug: "morocco", name: "Morocco", planning: "Regional routing and cultural preparation", weeks: 28, difficulty: 3 },
  { slug: "egypt", name: "Egypt", planning: "Site logistics and seasonal heat", weeks: 28, difficulty: 3 },
  { slug: "south-africa", name: "South Africa", planning: "Safari timing and internal travel", weeks: 36, difficulty: 3 },
  { slug: "kenya", name: "Kenya", planning: "Safari timing and vaccinations", weeks: 36, difficulty: 3 },
  { slug: "tanzania", name: "Tanzania", planning: "Safari and altitude considerations", weeks: 36, difficulty: 3 },
  { slug: "india", name: "India", planning: "Regional routing, health prep and pacing", weeks: 36, difficulty: 4 },
  { slug: "nepal", name: "Nepal", planning: "Trek permits and altitude acclimatisation", weeks: 40, difficulty: 4 },
  { slug: "thailand", name: "Thailand", planning: "Seasonal weather and island transport", weeks: 28, difficulty: 2 },
  { slug: "vietnam", name: "Vietnam", planning: "North-to-south routing and visas", weeks: 28, difficulty: 3 },
  { slug: "indonesia", name: "Indonesia", planning: "Inter-island transport", weeks: 32, difficulty: 3 },
  { slug: "china", name: "China", planning: "Visas, rail booking and connectivity", weeks: 36, difficulty: 4 },
  { slug: "south-korea", name: "South Korea", planning: "Transport and seasonal timing", weeks: 28, difficulty: 3 },
  { slug: "australia", name: "Australia", planning: "Vast distances and internal flights", weeks: 40, difficulty: 3 },
  { slug: "new-zealand", name: "New Zealand", planning: "Road-trip routing and seasons", weeks: 36, difficulty: 3 },
  { slug: "usa", name: "the USA", planning: "Internal distances and road-trip routing", weeks: 32, difficulty: 3 },
  { slug: "canada", name: "Canada", planning: "Seasonal access and distances", weeks: 32, difficulty: 3 },
  { slug: "mexico", name: "Mexico", planning: "Regional routing and safety research", weeks: 28, difficulty: 3 },
  { slug: "peru", name: "Peru", planning: "Altitude acclimatisation and trek permits", weeks: 36, difficulty: 4 },
  { slug: "brazil", name: "Brazil", planning: "Distances and regional variety", weeks: 36, difficulty: 3 },
  { slug: "argentina", name: "Argentina", planning: "Distances and seasonal timing", weeks: 36, difficulty: 3 },
  { slug: "chile", name: "Chile", planning: "Extreme length and seasonal access", weeks: 36, difficulty: 3 },
  { slug: "patagonia", name: "Patagonia", planning: "Weather windows and trek logistics", weeks: 44, difficulty: 4 },
  { slug: "turkey", name: "Turkey", planning: "Regional routing and seasonal timing", weeks: 24, difficulty: 2 },
  { slug: "jordan", name: "Jordan", planning: "Site logistics and desert conditions", weeks: 28, difficulty: 3 },
  { slug: "antarctica", name: "Antarctica", planning: "Expedition booking and serious budgeting", weeks: 80, difficulty: 5 },
];

function visitDestination(d: Destination): TemplateSpec {
  return {
    key: `travel-visit-${d.slug}`,
    title: `Travel to ${d.name}`,
    summary: `Plan and take a proper trip to ${d.name} — saved for, researched and booked rather than endlessly postponed. ${d.planning} is the part worth getting right.`,
    category: "project",
    difficulty: d.difficulty,
    weeks: d.weeks,
    tags: [d.slug.replace(/-/g, " "), d.name.toLowerCase(), "travel", "trip", "holiday"],
    skills: ["Budgeting and saving", "Research and itinerary", d.planning, "Bookings and documents", "Packing and preparation"],
    milestones: ["Budget set and saving started", "Dates and route decided", "Flights and accommodation booked", `Trip to ${d.name} taken`],
  };
}

const generated = DESTINATIONS.map(visitDestination);

const extras: TemplateSpec[] = [
  {
    key: "travel-solo-trip",
    title: "Take your first solo trip",
    summary: "Plan and take a trip alone — the logistics are easy, the nerve is the real work.",
    category: "project",
    difficulty: 3,
    weeks: 20,
    tags: ["solo travel", "independence", "first time", "confidence"],
    skills: ["Destination choice for solo travel", "Safety planning", "Comfort with your own company", "Meeting people while travelling"],
    milestones: ["Destination chosen and booked", "Solo day trip completed as practice", "Departed", "Trip completed"],
  },
  {
    key: "travel-backpacking",
    title: "Go backpacking for an extended trip",
    summary: "Long-term budget travel — money, kit, route and the realities of months on the road.",
    category: "project",
    difficulty: 4,
    weeks: 52,
    tags: ["backpacking", "long term travel", "budget", "gap year"],
    skills: ["Long-trip budgeting", "Minimal packing", "Flexible route planning", "Health and safety abroad", "Staying sane on the road"],
    milestones: ["Budget saved", "Route and visas sorted", "Departed", "Trip completed"],
  },
  {
    key: "travel-work-abroad",
    title: "Move abroad to live and work",
    summary: "Visas, work, housing and the practical reality of relocating your whole life.",
    category: "project",
    difficulty: 5,
    weeks: 60,
    tags: ["relocation", "expat", "visa", "moving abroad", "work"],
    skills: ["Visa and legal route", "Job search abroad", "Housing and logistics", "Finances across borders", "Building a life there"],
    milestones: ["Country and visa route chosen", "Job or income secured", "Moved", "Settled with a routine and a social circle"],
  },
  {
    key: "travel-digital-nomad",
    title: "Work remotely while travelling",
    summary: "Combine income and travel without wrecking either.",
    category: "project",
    difficulty: 4,
    weeks: 40,
    tags: ["digital nomad", "remote work", "travel", "location independent"],
    skills: ["Remote income security", "Time zone management", "Reliable connectivity planning", "Slow-travel rhythm", "Tax and legal awareness"],
    milestones: ["Income confirmed as portable", "First month working abroad", "Sustainable rhythm found", "Six months sustained"],
  },
  {
    key: "travel-road-trip",
    title: "Plan and take a long road trip",
    summary: "Route, vehicle, budget and stops — a trip that works rather than one that drags.",
    category: "project",
    difficulty: 2,
    weeks: 16,
    tags: ["road trip", "driving", "route", "travel"],
    skills: ["Route and stop planning", "Vehicle preparation", "Budgeting", "Flexible scheduling"],
    milestones: ["Route planned", "Vehicle and budget ready", "Departed", "Trip completed"],
  },
  {
    key: "travel-interrail",
    title: "Do a long rail journey",
    summary: "A multi-country trip by train, planned around routes and passes rather than flights.",
    category: "project",
    difficulty: 2,
    weeks: 20,
    tags: ["rail", "interrail", "train", "europe", "travel"],
    skills: ["Pass and reservation planning", "Route sequencing", "Light packing", "Budget management"],
    milestones: ["Route and pass chosen", "Reservations booked", "Departed", "Journey completed"],
  },
  {
    key: "travel-learn-language-for-trip",
    title: "Learn enough language before a trip",
    summary: "Targeted, practical language prep so you can actually interact rather than point.",
    category: "language",
    difficulty: 2,
    weeks: 14,
    tags: ["language", "travel", "phrases", "preparation"],
    skills: ["Survival phrases", "Numbers and directions", "Pronunciation", "Listening for key words"],
    milestones: ["Core phrases memorised", "Can order and ask directions", "Held a simple exchange", "Used it successfully on the trip"],
  },
  {
    key: "travel-photography-trip",
    title: "Come back with genuinely good travel photos",
    summary: "Plan light, locations and timing instead of taking a thousand forgettable snaps.",
    category: "creative",
    difficulty: 3,
    weeks: 20,
    tags: ["travel photography", "photos", "camera", "trip"],
    skills: ["Location and light scouting", "Composition", "Travel-light kit choices", "Editing and curation"],
    milestones: ["Kit and skills prepared", "Shot list planned", "Trip shot", "Edited series finished"],
  },
  {
    key: "travel-budget-trip",
    title: "Travel well on a small budget",
    summary: "Get the trip you want without the cost, through timing, routing and priorities.",
    category: "finance",
    difficulty: 2,
    weeks: 20,
    tags: ["budget travel", "cheap", "saving", "travel"],
    skills: ["Flexible date searching", "Accommodation alternatives", "Eating and transport locally", "Spending priorities"],
    milestones: ["Budget and priorities set", "Cheap flights secured", "Trip taken within budget", "Under budget without missing out"],
  },
  {
    key: "travel-family-trip",
    title: "Plan a trip that works with kids",
    summary: "Realistic pacing, accommodation and expectations for travelling as a family.",
    category: "project",
    difficulty: 3,
    weeks: 20,
    tags: ["family travel", "kids", "holiday", "planning"],
    skills: ["Realistic pacing", "Accommodation choice", "Activity balance", "Travel-day logistics"],
    milestones: ["Destination and dates chosen", "Accommodation booked", "Itinerary paced realistically", "Trip completed enjoyably"],
  },
  {
    key: "travel-visit-all-countries-region",
    title: "Visit every country in a region",
    summary: "A long-running multi-year travel project, tracked and sequenced properly.",
    category: "project",
    difficulty: 4,
    weeks: 200,
    tags: ["travel", "countries", "region", "long term"],
    skills: ["Long-horizon planning", "Efficient trip clustering", "Budget sustainability", "Record keeping"],
    milestones: ["List and plan made", "A quarter visited", "Half visited", "Every country visited"],
  },
  {
    key: "travel-overcome-flight-fear",
    title: "Overcome a fear of flying",
    summary: "Graded exposure and understanding, so flying stops limiting where you go.",
    category: "personal_development",
    difficulty: 3,
    weeks: 20,
    tags: ["fear of flying", "anxiety", "exposure", "travel"],
    skills: ["Understanding what you are hearing and feeling", "Anxiety regulation", "Graded exposure", "Support and preparation"],
    milestones: ["Understanding the mechanics", "Regulation techniques practised", "Short flight completed", "Long flight completed calmly"],
  },
];

export const travel: TemplateDomain = {
  key: "travel",
  label: "Travel",
  blurb: "Trips worth planning properly, moving abroad and travelling better.",
  templates: [...generated, ...extras],
};
