import type { TemplateDomain, TemplateSpec } from "../types";

/**
 * Wellbeing templates are structured as self-directed habit and skill work.
 * Anything clinical (an eating disorder, addiction, a diagnosed condition)
 * is framed around working WITH professional support rather than replacing
 * it — the plan tracks adherence and habits, not treatment.
 */

export const wellbeing: TemplateDomain = {
  key: "wellbeing",
  label: "Health & wellbeing",
  blurb: "Sleep, stress, mental health, habits and looking after yourself properly.",
  templates: [
    {
      key: "wellbeing-fix-sleep",
      title: "Fix your sleep",
      summary: "Build a sleep routine that actually produces rest, rather than more time in bed.",
      category: "habit",
      difficulty: 3,
      weeks: 16,
      tags: ["sleep", "insomnia", "routine", "rest"],
      skills: ["Consistent schedule", "Wind-down routine", "Light and caffeine management", "Sleep environment", "Tracking and adjusting"],
      milestones: ["Baseline tracked for a week", "Consistent bed and wake times", "Falling asleep reliably", "Waking rested most days"],
      metric: { name: "Average sleep", target: 8, unit: "hours" },
    },
    {
      key: "wellbeing-wake-early",
      title: "Become an early riser",
      summary: "Shift your wake time earlier and make it stick without permanent exhaustion.",
      category: "habit",
      difficulty: 3,
      weeks: 12,
      tags: ["early", "morning", "routine", "wake up"],
      skills: ["Gradual shifting", "Evening discipline", "Morning trigger", "Light exposure"],
      milestones: ["Bedtime moved earlier", "Target wake time hit on weekdays", "Two weeks consistent", "Sustained including weekends"],
    },
    {
      key: "wellbeing-meditation",
      title: "Build a meditation practice",
      summary: "Get past the first uncomfortable weeks to a practice that genuinely helps.",
      category: "habit",
      difficulty: 2,
      weeks: 16,
      tags: ["meditation", "mindfulness", "calm", "practice"],
      skills: ["Attention training", "Consistent daily slot", "Working with restlessness", "Extending duration"],
      milestones: ["Seven consecutive days", "Ten minutes daily for a month", "Twenty minutes comfortable", "Ninety days practised"],
      metric: { name: "Days practised", target: 90, unit: "days" },
    },
    {
      key: "wellbeing-manage-stress",
      title: "Get your stress under control",
      summary: "Identify your actual stressors and build responses that work under pressure.",
      category: "personal_development",
      difficulty: 3,
      weeks: 20,
      tags: ["stress", "anxiety", "coping", "resilience"],
      skills: ["Stressor identification", "Physiological regulation", "Boundary setting", "Recovery activities", "Early-warning awareness"],
      milestones: ["Triggers mapped", "Two techniques working reliably", "Boundaries actually held", "Noticeably lower baseline stress"],
    },
    {
      key: "wellbeing-anxiety-tools",
      title: "Build practical tools for anxiety",
      summary: "Evidence-based self-help techniques, used alongside professional support where appropriate.",
      category: "personal_development",
      difficulty: 3,
      weeks: 24,
      tags: ["anxiety", "mental health", "cbt", "coping"],
      skills: ["Thought recording", "Cognitive reframing", "Graded exposure", "Physiological regulation", "Support network"],
      milestones: ["Patterns identified in writing", "Reframing used in real situations", "One avoided situation faced", "Toolkit reliable under pressure"],
    },
    {
      key: "wellbeing-therapy",
      title: "Start and stay in therapy",
      summary: "Find the right professional, actually begin, and do the between-session work.",
      category: "personal_development",
      difficulty: 3,
      weeks: 32,
      tags: ["therapy", "counselling", "mental health", "support"],
      skills: ["Finding the right fit", "Preparing for sessions", "Between-session practice", "Tracking change"],
      milestones: ["Options researched", "First session attended", "Six sessions attended", "Meaningful change noticed"],
    },
    {
      key: "wellbeing-journal",
      title: "Keep a journal consistently",
      summary: "A regular writing practice for thinking clearly rather than performing insight.",
      category: "habit",
      difficulty: 1,
      weeks: 16,
      tags: ["journal", "writing", "reflection", "habit"],
      skills: ["Consistent trigger", "Useful prompts", "Honest writing", "Periodic re-reading"],
      milestones: ["Seven days in a row", "One month sustained", "Re-read and noticed patterns", "Three months sustained"],
    },
    {
      key: "wellbeing-gratitude",
      title: "Build a gratitude practice",
      summary: "A small daily practice with a genuinely good evidence base.",
      category: "habit",
      difficulty: 1,
      weeks: 10,
      tags: ["gratitude", "positivity", "habit", "wellbeing"],
      skills: ["Daily noting", "Specificity over generality", "Consistency"],
      milestones: ["Seven days", "One month", "Noticeable shift in default outlook"],
    },
    {
      key: "wellbeing-quit-smoking",
      title: "Quit smoking",
      summary: "A quit plan with substitution, trigger management and relapse recovery built in.",
      category: "habit",
      difficulty: 5,
      weeks: 32,
      tags: ["smoking", "quit", "nicotine", "addiction"],
      skills: ["Trigger mapping", "Substitution strategy", "Support and accountability", "Relapse recovery", "Long-term maintenance"],
      milestones: ["Quit date set and prepared", "One week smoke-free", "One month smoke-free", "Three months", "Six months smoke-free"],
      metric: { name: "Days smoke-free", target: 180, unit: "days" },
    },
    {
      key: "wellbeing-reduce-drinking",
      title: "Cut down or stop drinking",
      summary: "Reduce alcohol with a clear plan, honest tracking and social strategies that hold up.",
      category: "habit",
      difficulty: 4,
      weeks: 28,
      tags: ["alcohol", "drinking", "sober", "moderation"],
      skills: ["Honest baseline tracking", "Trigger and situation planning", "Alternatives", "Social scripts", "Support"],
      milestones: ["Baseline honestly tracked", "Target set and first week met", "One month at target", "Three months sustained"],
    },
    {
      key: "wellbeing-screen-time",
      title: "Cut your screen time",
      summary: "Reclaim hours a day from a habit designed to be hard to stop.",
      category: "habit",
      difficulty: 3,
      weeks: 12,
      tags: ["screen time", "phone", "digital", "focus"],
      skills: ["Usage tracking", "Friction and blockers", "Replacement activities", "Phone-free zones"],
      milestones: ["Baseline measured", "Friction in place", "Halved on weekdays", "Sustained for a month"],
      metric: { name: "Daily screen time", target: 2, unit: "hours" },
    },
    {
      key: "wellbeing-digital-detox",
      title: "Do a proper digital detox",
      summary: "A structured break from feeds, then a deliberate decision about what comes back.",
      category: "habit",
      difficulty: 3,
      weeks: 8,
      tags: ["detox", "social media", "digital", "attention"],
      skills: ["Removing access", "Boredom tolerance", "Replacement activities", "Deliberate reintroduction"],
      milestones: ["Apps removed", "One week without", "One month without", "Reintroduced deliberately, not by default"],
    },
    {
      key: "wellbeing-quit-porn",
      title: "Break a compulsive habit",
      summary: "A structured approach to compulsive behaviour, with support and relapse planning built in.",
      category: "habit",
      difficulty: 4,
      weeks: 32,
      tags: ["compulsion", "habit", "recovery", "self-control"],
      skills: ["Trigger identification", "Environmental friction", "Replacement behaviours", "Accountability", "Relapse recovery without spiralling"],
      milestones: ["Triggers and patterns mapped", "Two weeks clear", "One month clear", "Three months clear"],
    },
    {
      key: "wellbeing-drink-water",
      title: "Actually drink enough water",
      summary: "A trivially small habit that most people still fail to make automatic.",
      category: "habit",
      difficulty: 1,
      weeks: 6,
      tags: ["water", "hydration", "habit", "health"],
      skills: ["Visible cues", "Routine anchoring", "Tracking"],
      milestones: ["Cue in place", "One week consistent", "One month automatic"],
    },
    {
      key: "wellbeing-health-checkup",
      title: "Get on top of your health admin",
      summary: "The appointments and screenings you have been putting off, cleared in one campaign.",
      category: "project",
      difficulty: 1,
      weeks: 12,
      tags: ["health", "checkup", "dentist", "screening", "admin"],
      skills: ["Inventory of what is overdue", "Booking and follow-through", "Record keeping"],
      milestones: ["List of overdue items made", "First appointment attended", "Half cleared", "All appointments up to date"],
    },
    {
      key: "wellbeing-posture-breathing",
      title: "Learn to breathe and sit better",
      summary: "Small daily corrections to breathing and posture with outsized effects on tension.",
      category: "habit",
      difficulty: 2,
      weeks: 12,
      tags: ["breathing", "posture", "tension", "body"],
      skills: ["Diaphragmatic breathing", "Postural awareness", "Movement breaks", "Daily practice"],
      milestones: ["Technique understood", "Daily practice established", "Noticing and correcting automatically", "Reduced daily tension"],
    },
    {
      key: "wellbeing-burnout-recovery",
      title: "Recover from burnout",
      summary: "A slow, deliberate recovery rather than pushing through and relapsing.",
      category: "personal_development",
      difficulty: 4,
      weeks: 32,
      tags: ["burnout", "recovery", "rest", "work"],
      skills: ["Honest workload assessment", "Boundary setting", "Genuine rest", "Reintroducing demand gradually", "Preventing recurrence"],
      milestones: ["Situation honestly assessed", "Load actually reduced", "Energy beginning to return", "Sustainable pattern established"],
    },
    {
      key: "wellbeing-loneliness",
      title: "Build a social life that supports you",
      summary: "Treat connection as something you build deliberately, not something that just happens.",
      category: "personal_development",
      difficulty: 3,
      weeks: 32,
      tags: ["loneliness", "friendship", "connection", "social"],
      skills: ["Regular exposure to people", "Initiating contact", "Following up", "Deepening a few relationships"],
      milestones: ["One recurring social activity", "Three people contacted regularly", "A genuine friendship deepened", "Reliable social rhythm"],
    },
    {
      key: "wellbeing-confidence",
      title: "Build genuine self-confidence",
      summary: "Confidence from accumulated evidence rather than affirmations.",
      category: "personal_development",
      difficulty: 3,
      weeks: 28,
      tags: ["confidence", "self-esteem", "growth", "courage"],
      skills: ["Small deliberate discomfort", "Evidence logging", "Self-talk awareness", "Skill competence"],
      milestones: ["Comfort-zone edges identified", "Ten small challenges completed", "A significant fear faced", "Noticeably more willing to act"],
    },
    {
      key: "wellbeing-body-image",
      title: "Improve your relationship with your body",
      summary: "Shift from appearance-driven metrics to capability and health, with support where needed.",
      category: "personal_development",
      difficulty: 4,
      weeks: 36,
      tags: ["body image", "self-esteem", "health", "mindset"],
      skills: ["Media and comparison awareness", "Capability-based goals", "Self-talk work", "Professional support where appropriate"],
      milestones: ["Comparison triggers identified", "Goals reframed around capability", "Noticeably kinder self-talk", "Sustained change in relationship"],
    },
    {
      key: "wellbeing-grief",
      title: "Work through grief",
      summary: "Give loss the time and structure it needs, with support rather than alone.",
      category: "personal_development",
      difficulty: 4,
      weeks: 52,
      tags: ["grief", "loss", "bereavement", "healing"],
      skills: ["Allowing the process", "Support network", "Ritual and remembrance", "Gradual re-engagement"],
      milestones: ["Support in place", "Routines partially rebuilt", "Able to remember without being overwhelmed", "Re-engaged with life"],
    },
    {
      key: "wellbeing-adhd-systems",
      title: "Build systems that work with your brain",
      summary: "External structure for focus and memory instead of relying on willpower.",
      category: "personal_development",
      difficulty: 3,
      weeks: 24,
      tags: ["adhd", "focus", "systems", "executive function"],
      skills: ["External capture system", "Visible reminders", "Task decomposition", "Body doubling and accountability", "Forgiving reset routines"],
      milestones: ["Capture system running", "Nothing important held in memory alone", "Reset routine used after slips", "System survives a bad week"],
    },
    {
      key: "wellbeing-nutrition-basics",
      title: "Learn what to actually eat",
      summary: "Cut through diet noise to a sustainable, evidence-based way of eating.",
      category: "education",
      difficulty: 2,
      weeks: 16,
      tags: ["nutrition", "diet", "eating", "health"],
      skills: ["Macronutrient basics", "Reading evidence critically", "Practical meal construction", "Sustainable adjustment"],
      milestones: ["Baseline diet honestly logged", "Principles understood", "Meals adjusted", "New pattern sustained for a month"],
    },
    {
      key: "wellbeing-strength-for-longevity",
      title: "Train for a healthy old age",
      summary: "Build the strength, balance and capacity that predict independence decades from now.",
      category: "fitness",
      difficulty: 3,
      weeks: 52,
      tags: ["longevity", "healthspan", "strength", "ageing"],
      skills: ["Resistance training", "Balance and stability", "Cardiovascular base", "Mobility", "Long-term consistency"],
      milestones: ["Baseline capacity tested", "Training three times weekly", "Measurable strength gains", "One year of consistency"],
    },
  ],
};
